### ISSUE TITLE
Add Input Time Debugging to Logger

### ISSUE THREAD

**Issue by bloodmc** [streetpea/chiaki-ng#115]
Device: ROG Ally Z1 Extreme
OS: Windows 11 22H2
Chiaki build: latest windows release
1080P, 60FPS, 30000 bitrate

Using the latest windows Chiaki build on ROG Ally, I am experiencing a slight input delay of about .5 seconds. This becomes very noticeable in games such as Doom Eternal and Dead Space. Is there any documentation on how to configure settings to improve the input delay? 
Also, could you add input debugging for response time in logs?

**Comment by streetpea** [comment]
The biggest thing would be to hardwire your ps5 (via Ethernet) if it isn't already. Beyond that, I would try the following list of things https://streetpea.github.io/chiaki4deck/setup/configuration/#troubleshooting-performance-issues and see if they help your situation

**Comment by bloodmc** [comment]
Turns out ROG Ally can cause ping spikes when using Silent Mode power template. Swapping to Performance+ fixes ping time and improves input delay. However, I can still feel a small delay. Would it be possible to add input debugging to the logger? This way I can turn on verbose logging and see if my response times have improved or got worse based on settings I've changed.

Thanks!

**Comment by streetpea** [comment]
@jbaiter would the performance overlay you were thinking of have this kind of info (i.e., ping time, etc.)?

**Comment by jbaiter** [comment]
I'm not sure, we get the current round trip time from the console, that might be related to the input lag, but I'm currently not 100% sure how to interpret the value, since it's quite different from the ping times I'm getting from the console. Need to investigate more.
