### ISSUE TITLE
Video glitches every 5-10 seconds - please help!

### ISSUE THREAD

**Issue by shaneo632** [streetpea/chiaki-ng#155]
Ever since I got the Steam Deck OLED I've been having major issues with Chaiki4Deck. I've tried all the recommended settings for Chiaki4Deck with the HDR update but they all cause the image to break up every 5-10 seconds as seen in the God of War Ragnarok video on this Reddit thread I made (https://www.reddit.com/r/SteamDeck/comments/190w5fo/chaiki4deck_issues_ever_since_getting_the_oled/).

I've tried reducing the video quality, changing settings in my router, and nothing has helped. I'm totally convinced it's something to do with the Deck's WiFi settings. I've also disabled the wifi power management setting in the developer menu but it hasn't helped sadly.

I'm getting so frustrated because I love using Chiaki and I just can't use it to reliably play games at the moment, it's driving me mad. Any help would be so so appreciated. Thanks :) I've included a log below from one of the instances where the image broke up. If anyone can help identify the problem I would be so grateful, cheers.

[chiaki_session_2024-01-07_20-11-51-611611.log](https://github.com/streetpea/chiaki4deck/files/13854842/chiaki_session_2024-01-07_20-11-51-611611.log)

**Comment by hvmzx** [comment]
Try this, fixed everything for me : https://github.com/streetpea/chiaki4deck/issues/103#issuecomment-1846414293

**Comment by plexecutor** [comment]
> Try this, fixed everything for me : [#103 (comment)](https://github.com/streetpea/chiaki4deck/issues/103#issuecomment-1846414293)

I made this change and it didn't fix anything for me. My session still lasts for about 20 minutes before the stuttering starts and soon after I lose all inputs. Only fix is to force close and reconnect.

**Comment by hvmzx** [comment]
Ah too bad, I wish it resolved it. I didn't expect it to work so well

**Comment by bloodmc** [comment]
> Ever since I got the Steam Deck OLED I've been having major issues with Chaiki4Deck. I've tried all the recommended settings for Chiaki4Deck with the HDR update but they all cause the image to break up every 5-10 seconds as seen in the God of War Ragnarok video on this Reddit thread I made (https://www.reddit.com/r/SteamDeck/comments/190w5fo/chaiki4deck_issues_ever_since_getting_the_oled/).
> 
> I've tried reducing the video quality, changing settings in my router, and nothing has helped. I'm totally convinced it's something to do with the Deck's WiFi settings. I've also disabled the wifi power management setting in the developer menu but it hasn't helped sadly.
> 
> I'm getting so frustrated because I love using Chiaki and I just can't use it to reliably play games at the moment, it's driving me mad. Any help would be so so appreciated. Thanks :) I've included a log below from one of the instances where the image broke up. If anyone can help identify the problem I would be so grateful, cheers.
> 
> [chiaki_session_2024-01-07_20-11-51-611611.log](https://github.com/streetpea/chiaki4deck/files/13854842/chiaki_session_2024-01-07_20-11-51-611611.log)

To rule out Wi-Fi/router issues, can you test using an Ethernet adapter? If that still causes issues, bypass router and do another test directly connected to modem.

**Comment by plexecutor** [comment]
> > Ever since I got the Steam Deck OLED I've been having major issues with Chaiki4Deck. I've tried all the recommended settings for Chiaki4Deck with the HDR update but they all cause the image to break up every 5-10 seconds as seen in the God of War Ragnarok video on this Reddit thread I made (https://www.reddit.com/r/SteamDeck/comments/190w5fo/chaiki4deck_issues_ever_since_getting_the_oled/).
> > I've tried reducing the video quality, changing settings in my router, and nothing has helped. I'm totally convinced it's something to do with the Deck's WiFi settings. I've also disabled the wifi power management setting in the developer menu but it hasn't helped sadly.
> > I'm getting so frustrated because I love using Chiaki and I just can't use it to reliably play games at the moment, it's driving me mad. Any help would be so so appreciated. Thanks :) I've included a log below from one of the instances where the image broke up. If anyone can help identify the problem I would be so grateful, cheers.
> > [chiaki_session_2024-01-07_20-11-51-611611.log](https://github.com/streetpea/chiaki4deck/files/13854842/chiaki_session_2024-01-07_20-11-51-611611.log)
> 
> To rule out Wi-Fi/router issues, can you test using an Ethernet adapter? If that still causes issues, bypass router and do another test directly connected to modem.

I tested streaming with a usb-c to ethernet adapter on my OLED deck last night and this morning and I was able to stream for over an hour during both sessions without a single glitch. Definitely seems to be specific to wifi on the OLED model decks. Possibly a Steam OS issue with the new wifi NIC? Unfortunately I do not have access to a non-OLED deck using the older wifi NIC to do more thorough testing.

**Comment by bloodmc** [comment]
See https://github.com/ValveSoftware/SteamOS/issues/1256
