### ISSUE TITLE
Regist Search failed

### ISSUE THREAD

**Issue by 6ky** [streetpea/chiaki-ng#193]
I downloaded the app image from GitHub and executed it and then tried adding my account which resulted in Regist Search failed. Prior to this from the discovery store version I tried linking the account and it keeps saying invalid PSN ID.

**Comment by Benyo85** [comment]
Unfortunately I still have the error CE-110032-7. Despite version 1.6.1 the registration does not work. Invalid PSN ID

**Comment by Kamron92** [comment]
Hello! I have another problem. After port forwarding I'm trying manually register my ps5 but nothing happens. I can only delete created ps5 profile, no connection and registration. There is a window with status for a second with the last words:

-Regist received unknown key RP-SupportCmd in response payload
- Regist successfully received response

**Comment by streetpea** [comment]
@Kamron92 you can now select from all previously registered ps5s for remote connection (will be included in next release) and if you want to register manually via a remote ip (non local connection) you need to also port forward udp 9295
