### ISSUE TITLE
[BUG]Frequent frame drops and stutters on version 1.6.2 Windows version

### ISSUE THREAD

**Issue by Colindm8** [streetpea/chiaki-ng#224]
**Describe the bug**
I'm getting frequent frame drops and stutters on 1.6.2. Frame rate constantly fluctuating between low 50s and 60. I don't get these issues at all on 1.6.1.

**Debug Log**

[chiaki_session_2024-01-22_20-29-55-977977.log](https://github.com/streetpea/chiaki4deck/files/14015220/chiaki_session_2024-01-22_20-29-55-977977.log)

**To Reproduce**
Open ps5 session and play. Experience frequent stutters. 

**Expected behavior**
Minimal stutters as in 1.6.1

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version
 - Device ROG Ally
 - Chiaki4deck Version 1.6.2

**Additional context**

**Comment by dadzaumnos** [comment]
Same issue here since 1.6 update, however, on Steam Deck.
Rollback to 1.5.1 works fine.

Some people are also complaining about stuttering on 1.6 on Reddit, maybe some post processing introduced this on the new version.

**Comment by streetpea** [comment]
Fixed in the newer versions. Try 1.8.1
