### ISSUE TITLE
Allow custom ports when adding a new device to Chiaki

### ISSUE THREAD

**Issue by afrozenpeach** [streetpea/chiaki-ng#242]
**Is your feature request related to a problem? Please describe.**
We have two PS5s in the house, and would love to both be able to use remote play on those PS5s while outside the house. Theoretically it would be possible if we had Chiaki connect to a remote IP address using a specific port(s) so we could assign different ports to different PS5s.

**Describe the solution you'd like**
PS5 remote play currently uses ports 9295-9297, 9302-9305, and 987. It would be awesome to configure those 3 ranges so that the router could forward new ports to those ranges internally.

**Comment by streetpea** [comment]
@jbaiter would #123 allow for multiple consoles to be used simultaneously?

**Comment by jbaiter** [comment]
> @jbaiter would #123 allow for multiple consoles to be used simultaneously?

I *think* it would, but not 100% certain.

@afrozenpeach does it work with the official app? Can you remote play on multiple consoles with the same PSN account?

**Comment by afrozenpeach** [comment]
@jbaiter actually it might! i'll find out today and get back to you

**Comment by afrozenpeach** [comment]
@jbaiter @streetpea I did some extensive testing and it seems that both chiaki and the official remote play app seem to use the same ports. I can't come up with another way of making two remote play connections at once, besides allowing custom ports on the Chiaki side of things.

**Comment by jbaiter** [comment]
Thanks for testing, so even when using two PSN accounts with the official app two concurrent sessions are not possible if both consoles are behind the same NAT?

**Comment by afrozenpeach** [comment]
Correct. It seems both cnosoles attempt to connect to the same ports on the shared router, and (in my testing) one or both failed to connect.

My theory is that if Chiaki could connect to ports 4040-4050, and the NAT could forward 4040-4050 [PSN's actual ports internally] it'd work flawlessly.

**Comment by streetpea** [comment]
@afrozenpeach can you try with the remote connection via psn added to Chiaki4deck?
