### ISSUE TITLE
[Feedback] Configuration - /setup/configuration/

### ISSUE THREAD

**Issue by GhostYotaz** [streetpea/chiaki-ng#246]
Can’t seem to find a solution to this. I get connected to the stream for 1-2 seconds with no visuals on the Steam deck. PS5 says remoteplay connected and then disconnects directly after. On the steam deck it days ”Remote play stream failed! Reason: Nagane did not innit” what does it mean? How can i solve this?

**Comment by jbaiter** [comment]
Debug log please.
