### ISSUE TITLE
[BUG] Gyro jumps to position depending on real world controller orientation

### ISSUE THREAD

**Issue by dEEkAy2k9** [streetpea/chiaki-ng#259]
**Describe the bug**
Running chiaki4deck on windows 11 with a dual sense (ps5) connected via usb. Same goes for running it via steam but with steam input disabled.
In games that use gyro (like resident evil 4 remake) the starting position of the gyro seems to be dependend on where the controller is pointed at. This means, resting the pad in your lap and using L2 to aim (gyro is enabled ingame ofc), the crosshair jumps to a certain position.

**Debug Log**
[chiaki_session_2024-02-25_15-59-25-675675.log](https://github.com/streetpea/chiaki4deck/files/14396748/chiaki_session_2024-02-25_15-59-25-675675.log)

**To Reproduce**
1. Start game with native gyro support but the gyro is set to activate while aiming only (L2 in Resident Evil 4 Remake for example)
2. Use dual sense (ps5) wired via usb
3. Make sure steam input is disabled
4. Hold still, press L2.
5. Depending on where you actually aim your controller in the real world, initial crosshair position will jump towards that when activated.

**Expected behavior**
On games that use gyro but only activate it while aiming, the crosshair/ironsights should not jump to a initial position. The position you are holding your game when starting should not have any impact on this.

**Video**
https://github.com/streetpea/chiaki4deck/assets/15087108/f31c2bd5-ff80-4e5e-ad85-4ed9ed9b1171
In this Video i have been holding the controller still and only activated L2 where the games default gyro kicks in. Depending on the initial position of the pad, crosshair (red dot) jumps to.

**Desktop (please complete the following information):**
- Windows 11 Version 23H2 (Build 22631.3155)
- Chiaki4deck Version 1.6.3
- PS5 streaming over LAN to PC

**Comment by dEEkAy2k9** [comment]
Just tested this on the official ps remote play app. It doesn't happen there.
Any ideas what might cause this?

**Comment by dEEkAy2k9** [comment]
i have noticed that this issue happens on mirrorplay on ios too (psplay for ios, just different name). Once a dual sense is connected via usb-c to the phone and games like re4remake engage gyro on left trigger pull, initial position depends on real world position of the controller. This then leads to jumping.

The official ps remote play app from sony does not exhibit this behaviour, but it lags significantly compared to chiaki4kdeck, mirrorplay etc.

**Comment by streetpea** [comment]
@dEEkAy2k9 can you replicate this on other games? (I'm asking because I don't have Resident Evil 4 Remake to test it)

**Comment by tenphi** [comment]
I have tested several games already. Every game works fine (better than dualsense actually, love it!) except Resident Evil 4. In RE4, every time I start aiming, the aim jumps down.
Sadly, I don't have other RE games like Village. But I suspect they have the same issue.
I strongly believe it's not an issue with Chiaki but with the game itself.
The bug can be reproduced with Steam Deck controls, not only DualSense. Very weird.

**Comment by dEEkAy2k9** [comment]
> @dEEkAy2k9 can you replicate this on other games? (I'm asking because I don't have Resident Evil 4 Remake to test it)

Sorry, i have been out of loop for some time.
Since only a few games actually utilize the gyro i couldn't test it with other games yet. I might test it with RE8 (Village) and i could try it with The Finals. But this might not happen super fast though as i a busy currently.



> I have tested several games already. Every game works fine (better than dualsense actually, love it!) except Resident Evil 4. In RE4, every time I start aiming, the aim jumps down. Sadly, I don't have other RE games like Village. But I suspect they have the same issue. I strongly believe it's not an issue with Chiaki but with the game itself. The bug can be reproduced with Steam Deck controls, not only DualSense. Very weird.

Did you test the games own gyro or did you map it through steam since you mentioned the steam deck?
I actually tried RE4 through the steam deck with chiaki too and using steam input felt different but hasn't had that issue, it only appeared when i used the games own gyro implementation and didn't use steam input.

The og PS Remote Play app from Sony doesn't exhibit this behavior but that one is laggy.

**Comment by streetpea** [comment]
@dEEkAy2k9 it turns out there is a demo for re4 remake so I was able to test it and replicate the issue you’re describing. I’m looking into a fix.

**Comment by streetpea** [comment]
@dEEkAy2k9 here is the build you should use https://github.com/streetpea/chiaki-ng/actions/runs/12065799882/artifacts/2248743349
