### ISSUE TITLE
[BUG]  screen freezes after a few hours

### ISSUE THREAD

**Issue by Kazakiri** [streetpea/chiaki-ng#260]
**Describe the bug**
Everything works fine when in use, but after two to three hours, Chiaki's screen freezes completely. During this time, the PS5 controller still responds, indicating that the connection is not lost. I have to turn off Chiaki and reconnect to get the screen back to normal

**Debug Log**
https://mega.nz/file/15tFEK7R#e8Mhk3W5sHH0euynXRPivAVUqtBCFk6IdBdurQnxeyQ

**To Reproduce**
After playing for two to three hours or longer each time

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 23H2
 - Device PC
 - Chiaki4deck Version 1.6.3

**Comment by lyndonguitar** [comment]
also happens to me. the screen freezes and i get some weird audio crackling. I immediately quit Chiaki and reconnect and its fine again.

**Comment by streetpea** [comment]
I was able to reproduce after about 8 hours of streaming
