### ISSUE TITLE
Change a way of entering or exiting full screen mode

### ISSUE THREAD

**Issue by M4K1SAMA** [streetpea/chiaki-ng#268]
I'm playing games on Windows, and the experience is wonderful. But one thing is that the touchpad is mapped to the cursor. When I press touchpad in games, the program maybe recognizes it as double click and somehow quit full screen mode, which is pretty annoying.
I think the function should be bound with the key 'Esc' or something else instead? Should be pretty simple.

**Comment by streetpea** [comment]
You can already use F10 to enter full screen mode.
