### ISSUE TITLE
[MacOS] Access to network not working after restart of chiaki4deck

### ISSUE THREAD

**Issue by AkaP88** [streetpea/chiaki-ng#275]
Hello,

I use Chiaki4Deck ARM64 on MacOS 14.2.1 (23C71).

Usually Chiaki4Deck (and Chiaki) asks for permissions to access local network. Once it is granted, it can discover my PS5 and work with no issues.

Recently the first time I launch Chiaki4Deck, the permission is requested and everything work as expected. If I close Chiaki4Deck and run it again, it doesn't ask for permission and doesn't discover the PS5. Adding the PS5 manually doesn't work either since the packet sent through the network is not reaching the PS5. Seems that MacOS is not allowing Chiaki4Deck to access the network. Restarting MacOS and running Chiaki4Deck again seems the only solution so far.

I didn't either find a different way to force MacOS to give local network access to Chiaki.

Any Idea?

Thank you

**Comment by streetpea** [comment]
Maybe this is helpful: https://apple.stackexchange.com/questions/458409/after-denying-an-app-network-permissions-how-do-i-explicitly-allow-an-applicati

**Comment by streetpea** [comment]
@Amine-Kamoun have you tried manually adding the application to in Apple menu -> system settings -> network -> firewall ?

**Comment by streetpea** [comment]
Manually adding to firewall as described above will fix this so I’m closing
