### ISSUE TITLE
[BUG] Windows release since 1.6.0 shows only blank screen

### ISSUE THREAD

**Issue by policeman0077** [streetpea/chiaki-ng#305]
**Describe the bug**
Windows release since 1.6.0 shows only blank screen. I tried 1.6.0 to 1.6.5 they all show a blank screen after I double click the program. 1.5.0 runs on my machine. Tried on both win10 and win11 have same issue. Both machines have nvidia gpus.

**Debug Log**
[chiaki1.6.3.LOG](https://github.com/streetpea/chiaki4deck/files/14895221/chiaki1.6.3.LOG)

**To Reproduce**
1. Unzip the package
2. Double click on 'Chiaki.exe'
3. See a blank screen

**Expected behavior**
See the GUI after run the program

**Screenshots**
![Snipaste_2024-04-05_10-57-31](https://github.com/streetpea/chiaki4deck/assets/982502/2e8be391-1989-452e-9063-f3da6bebc67f)

**Desktop (please complete the following information):**
 - OS: windows
 - Version 11 and 10
 - Device PC
 - Chiaki4deck Version 1.6.0 - 1.6.5

**Comment by robpinheiro** [comment]
The same happens to me
Windows 10
laptop device
Integrated graphics Intel(R) UHD Graphics 630
Offboard device RTX2060

The screen turns white and then the software closes.
Version 1.50 runs normally
Does not generate any logs in C:\Users\UserProfile\AppData\Roaming\chiaki

**Comment by streetpea** [comment]
you can download and run debug view https://download.sysinternals.com/files/DebugView.zip and launch it in the background and see what comes up on there when running Chiaki4deck to see what's happening on your system.

**Comment by policeman0077** [comment]
> you can download and run debug view https://download.sysinternals.com/files/DebugView.zip and launch it in the background and see what comes up on there when running Chiaki4deck to see what's happening on your system.

here is the dump from debug view
[chiaki1.6.3.LOG](https://github.com/streetpea/chiaki4deck/files/14895192/chiaki1.6.3.LOG)

**Comment by policeman0077** [comment]
I feel it is relate to #239. Is there anyway I can set libplacebo to use d3d by default?

**Comment by streetpea** [comment]
@policeman0077 have you tried disabling the graphics-hook.dll from obs that shows up here in your logs?

Maybe that's what's interfering. The other issue you linked is when the Vulkan hw decoder is used with ffmpeg but doesn't take effect until you start the stream. So you are just loading the main menu (which doesn't use ffmpeg or Vulkan hw decoding itself) that wouldn't cause this.

 graphics-hook.dll loaded against process: chiaki.exe

**Comment by streetpea** [comment]
@policeman0077 also do you have Vulkan installed directly on your computer? (sometimes that version will be used instead of the version provided with chiaki4deck which will interfere and could cause this since chiaki4deck is built with a specific version)

**Comment by policeman0077** [comment]
> @policeman0077 also do you have Vulkan installed directly on your computer? (sometimes that version will be used instead of the version provided with chiaki4deck which will interfere and could cause this since chiaki4deck is built with a specific version)

I tried Chiaki4deck-win_x64-VC-1.6.6 this version works on my computer. Don't known what's the difference? Compiler?

**Comment by policeman0077** [comment]
> Chiaki4deck-win_x64-VC-1.6.6

And latest version 1.7.2 using mysys2 to compile also working. I tried select different api (auto/vulkan/d3d) they all worked.

**Comment by streetpea** [comment]
@policeman0077 is 1.6.3 still broken or does that work now (ruling out a change in your system causing it to work now)?

**Comment by streetpea** [comment]
Since according to @policeman0077 his issue is resolved, I’m closing this.
