### ISSUE TITLE
[BUG] HDR on Stellar Blade

### ISSUE THREAD

**Issue by x4ndman** [streetpea/chiaki-ng#337]
**Describe the bug**
I have Stellar Blade set to HDR. But when connecting with chiaki4deck the HDR option is disabled. However, steam deck OLED has the HDR option enabled in the brightness settings.

**Debug Log**
Please attach a log with verbose logging enabled.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. SteamOS]
 - Device [e.g. Steam Deck]
 - Chiaki4deck Version [e.g. 1.6.2]

**Additional context**

**Comment by streetpea** [comment]
Do you have your connected hdr tv on when playing Stellar Blade. For some games hdr requires and tv models the game requires the tv to be on and send the signal to the ps to enable hdr.

**Comment by x4ndman** [comment]
As far as ive tried yesterday, tv was on. But the settings in Stellar Blade still said no HDR detected.

**Comment by streetpea** [comment]
@x4ndman just to confirm your tv is hdr?

**Comment by x4ndman** [comment]
Yes it is. I am using LG C2 Oled.
However, yesterday, i did try again, and the HDR option is enabled. I did nothing different. And the TV was even off. 😅😅😅. But theres something else i noticed. When HDR is on and TV is on, my connection will stutter after a few mins. Is this a one off or common issue i am not certain. Will try again and see if it happens again.

**Comment by streetpea** [comment]
On my tv it works fine with hdr enabled. Having said that, there are some ppl who have mentioned having the hdmi cable plugged into their tv hurt remote play performance. If there is some truth to that I would have to imagine it would be some setting on the tv causing it (as most have no problems with hdmi plugged in) … have you tried disabling hdmi cec and vrr for the ps5 input and see if maybe that helps. Those are the only things I could think that would be set on the tv. Come to think of it though a couple of ppl have mentioned using lg c2 with hdr seemingly without this issue so maybe it is just a random network problem.

**Comment by x4ndman** [comment]
Ah thats interesting. Will have a go at this later. Hope it's just network instability issue. Will report back the findings once i am done. Btw thank you for this awesome work! It helps me utilise my Deck more and save some money from getting PS Portal! U the best!

**Comment by streetpea** [comment]
@x4ndman since it seems like it wasn’t an issue with Chiaki-ng itself but the ps5 not streaming hdr to Chiaki-ng, I’m closing this. If you need something else please reopen.
