### ISSUE TITLE
[BUG] Frame drops and major stuttering when using a bluetooth controller 

### ISSUE THREAD

**Issue by tnysl** [streetpea/chiaki-ng#339]
**Describe the bug**
When using Chiaki4Deck with the default steamdeck controls (on the physical steamdeck) it runs absolutely flawlessly but when I connect my PS5 controller through bluetooth the performance starts having major sutterring and frame drops. I’ve tested it with two different controllers and the controllers still work perfectly fine with steam native games. 

Desktop
 - OS: SteamOS
 - Version: 3.5.19
 - Device: SteamDeck
 - Chiaki4deck Version: 1.7.0

**Comment by streetpea** [comment]
@tnysl have you tried using the Bluetooth controller with other streaming services. It’s possible your WiFi is being affected when a bluetooth controller is connected. As far as Chiaki4deck it uses sdl to handle Bluetooth and usb connections so there is no difference there.

**Comment by Entropy512** [comment]
2.4 GHz or 5 GHz wifi?

If 2.4, this is an expected result due to interference between two interfaces operating in the same frequency band and not a bug.

**Comment by streetpea** [comment]
As mentioned, interference is expected at 2.4 GHz. Please use 5 or 6 GHz to avoid interference.
