### ISSUE TITLE
Local hotspot without internet connection

### ISSUE THREAD

**Issue by chq1976** [streetpea/chiaki-ng#351]
Hi,

is it possible, to play with chiaki4deck on a steamdeck, when the ps 5 is wired to a wlan router without internet connection. The wlan router (an airport express for example) should then make a local wlan, to which the steamdeck is connected to.

Greetz Chris

**Comment by streetpea** [comment]
@chq1976 Yes it should discover it on the private subnet (LAN) of the router and work if local devices are allowed to connect to wired devices on the local network (setting in router). If they are connec free d locally external internet access is not needed.

**Comment by chq1976** [comment]
Cool, i‘ll try!!

Greetz Chris

**Comment by streetpea** [comment]
Closing as asked and answered
