### ISSUE TITLE
[BUG] Chiaki not working on Legion GO - Black Screen, press L1+L3+R1+R3 message is displayed but no action

### ISSUE THREAD

**Issue by BobyMT** [streetpea/chiaki-ng#360]
**Describe the bug**
I've adjusted the resolution in the Chiaki settings and now it doesn't start anymore, only with a black screen:

![image](https://github.com/streetpea/chiaki4deck/assets/49160746/be9c5df0-2c17-4e0f-a5d6-18029dc23550)

PS5 is starting normally and I can hear the sounds of navigating the menu, but the screen remains black on the Legion GO.

Is there a way to reset the settings of the app so I can start it again on the console?

**Comment by streetpea** [comment]
I assume you are in autoconnect. Hit the back (b) button to exit autoconnect back to the settings menu. I wouldn’t think just adjusting the resolution would cause that though…

**Comment by BobyMT** [comment]
After further testing, I've managed to find the issue, it is related to the H265 HDR (PS5) codec, it causes the black screen and the settings dashboard can't be accessed at all, even after hitting the back button multiple times.
![image](https://github.com/streetpea/chiaki4deck/assets/49160746/1db3308e-7452-4dca-b1f4-511f9e534bf8)

I've managed to revert the settings by reverting to 1.6.0, then went to the latest version again.

**Comment by streetpea** [comment]
@BobyMT i thought you were on the autoconnect page not the stream page. Where you were ctrl+q is what have exited you to the menu.

**Comment by BobyMT** [comment]
I’ve set the H265 HDR codec again and CTRL + Q doesn’t work, however it worked on the non-HDR H265 codec. The HDR codec seems to be broken

**Comment by streetpea** [comment]
Huh it works fine on Steam Deck. It must be something with windows. What logs do you get?

**Comment by streetpea** [comment]
@BobyMT what’s happening is nothing is rendering bc for amd on Windows Vulkan doesn’t work with hdr (see #393). If you want to use hdr please switch to the d3d11va hw decoder from either auto or Vulkan. It should work then. Since it is actually the  hdr issue meaning the overlay just isn’t displaying when you click the stream menu (not an issue with the input itself) I’m closing this issue as that issue is being tracked in #393
