### ISSUE TITLE
Consider renaming the project

### ISSUE THREAD

**Issue by matteorizzello** [streetpea/chiaki-ng#369]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Renaming the project to better convey that this is not just a version of Chiaki for Steam Deck

**Describe alternatives you've considered**
Not renaming it because honestly it doesn't matter that much

**Additional context**
Over time, this app has evolved from just being an optimized version of Chiaki for the Steam Deck, to a much more improved and updated project which has incredibly useful features like connecting outside of the local network and a completely redone UI. I personally think chiaki4deck deserves its own name at this point. For example I thought of the name "Nanami", to preserve the reference to the character Chiaki was named after, and also because it sounds good, while on Flathub and Github it could be named "Nanami (chiaki4deck)" to make sure people who don't know of the name change (for example, people reading old guides) would not get confused by the new name while searching it up. I understand though this is completely up to the creator of the project, this is just a suggestion I have and I  completely understand if you disagree :)

**Comment by streetpea** [comment]
@matteorizzello a name change is actually underway behind the scenes but some things need to be taken care of first.

**Comment by streetpea** [comment]
The project has been renamed to chiaki-ng (i.e., chiaki-next-generation)
