### ISSUE TITLE
[BUG] Random vibration (rumble) with wireless Dualsens

### ISSUE THREAD

**Issue by Lulzsec616** [streetpea/chiaki-ng#374]
Hello !
Sorry for my broken English, I installed C4D which is an awesome application!
I connected my Dualsens wirelessly to the PC with a bluetooth dongle, but when I play Spiderman 2 or Astro bot, the controller vibrates randomly almost without stopping (The haptic feedback works well)
When I plug the controller into USB, everything works!
Do I need to carry out any manipulation?

**Comment by streetpea** [comment]
When DualSense is used wirelessly it uses rumble emulation for haptic vibration as real haptics are not available via Bluetooth. The rumble on the DualSense (when not in haptic feedback mode) is wanting and I believe that is what you are experiencing.
