### ISSUE TITLE
[BUG] Add to non steam shortcut racing condition crash steam library images/shortcuts.vdf

### ISSUE THREAD

**Issue by Originalimoc** [streetpea/chiaki-ng#380]
**Describe the bug**
Clicked create shortcut multiple times because not sure why took so long(aka. did it click?) then it added multiple times by modifying the steam database files? Has to reinstall steam to fix.

Fix:
Lock request button once clicked.

**Comment by Originalimoc** [comment]
Also the vdf backup file add a timestamp/random number so it won't be overwritten by multiple creation request

**Comment by Originalimoc** [comment]
I tried shortcut creation again(in desktop mode, steam closed) in a new account. It still make all images of custom games which is fine before creation, disappearing.. Didn't you encounter this bug? @streetpea

**Comment by streetpea** [comment]
Nope works fine for me .. I haven’t had a report of this from any other users either
