### ISSUE TITLE
HDR Capping at ~400 Nits

### ISSUE THREAD

**Issue by Wiggyweir** [streetpea/chiaki-ng#381]
HDR is not working correctly. Image is very dim and looks washed out

HDR icon is displayed in Steam OS. however, when viewing the steam decks HDR visualisation, the maxcll is just under 400 bits.

SDR looks significantly better, when compared

 - OS: SteamOS 
 - Version 3.5.19
 - Device Steam Deck
 - chiaki-ng Version 1.8.0

Correct codec is selected in Chiaki settings, HDR is calibrated to 15-15-0 in the PS5 settings 

PS5 Home Screen is also not showing correctly in HDR, despite the setting being to ‘Always On’

in ratchet and clank, I can get HDR to work but only when the ‘120Hz mode’ is set to Auto

![IMG_2116](https://github.com/user-attachments/assets/748087e1-c1e7-483c-8fa3-9708ed95d0c3)
![IMG_2115](https://github.com/user-attachments/assets/9e0f644e-3076-4391-ad45-8f05af542839)

**Comment by streetpea** [comment]
@Wiggyweir while hdr is active on the Steam Deck it is almost certain that hdr is not activated on the PS5 which is why you do not get above 400 nits. 

As noted in the docs https://streetpea.github.io/chiaki-ng/setup/configuration/#hdr-high-dynamic-range the hdr tv your ps5 is connected to may need to be turned on for hdr to activate on the PS5 (it depends on the tv/game).

**Comment by Wiggyweir** [comment]
Thanks for the reply, my TV has been on, displaying the PS5 signal the whole time

the more I’ve tested today it seems that games with a HDR toggle in the in game menu will work and will out out circa 1000nits or higher

games with no toggle will not show as HDR and will be capped at 400nits 

examples I’ve tested

ratchet and clank - HDR toggle present - working
COD4 Remastered - No HDR toggle - not working

**Comment by streetpea** [comment]
Ah it’s possible the game itself doesn’t support hdr then … is your tv displaying more than 400 nits for the game?

**Comment by Wiggyweir** [comment]
My TV is an LG C3 which is HDR compatible so it shouldn’t be that. And is on and displaying the PS5 signal

another example to outline which should answer your question is COD WW2, the game is HDR as it asks you to configure HDR white point when you boot the game. However, there’s no HDR ON/OFF toggle in the game so the game displays at 400nits

sorry, I hope this is making sense, I’m pretty sure I’m doing everything correct here 

it seems like unless there’s a discrete ‘Turn HDR on’ toggle in game the HDR doesn’t kick in

**Comment by streetpea** [comment]
@Wiggyweir there is essentially a toggle for allowing hdr with remote play which is on when you set the codec option on. There is also a toggle which sets hdr on on the SteamDeck which  you can tell is on by checking the hdr badge. Other than that, there is nothing else the client (i.e., chiaki-ng) can do relative to hdr. It is up to the ps to send an HDR stream at that point. In your case, it is not sending an hdr stream. I have only tested in a few games (cyberpunk, ghost of Tsushima, and baldurs gate 3) and hdr has worked in them. It seems for whatever reason, the game you are playing does not support hdr over remote play for whatever reason.
