### ISSUE TITLE
[BUG] chiaki-ng on Windows cannot take screenshots and window capture correctly from other applications

### ISSUE THREAD

**Issue by akaymd** [streetpea/chiaki-ng#384]
**Describe the bug**

When I try to take a screenshot of chiaki-ng from another application, it does not work.
If I do the same with the original Chiaki, it works fine.
Note that gameplay in chiaki-ng is working.

This causes the following problems:
- Can not get a window capture on [OBS](https://obsproject.com/).
- Can not get a screenshot with like the following python program

How can I get a correct screenshot?

```python
# pip install pywin32 opencv-python-headless numpy
import cv2
import numpy as np
import win32con
import win32gui
import win32ui

# This program works properly on original Chiaki
# hwnd = win32gui.FindWindow(None, "Chiaki | Stream")

# But does not work on chiaki-ng.
hwnd = win32gui.FindWindow(None, "chiaki-ng")

left, top, right, bottom = win32gui.GetWindowRect(hwnd)
_, _, width, height = win32gui.GetClientRect(hwnd)
margin_x = right - left - width
margin_y = bottom - top - height
offset_x = int(margin_x / 2)
offset_y = margin_y - offset_x

win_dc = win32gui.GetWindowDC(hwnd)
src_dc = win32ui.CreateDCFromHandle(win_dc)
mem_dc = src_dc.CreateCompatibleDC()

bmp = win32ui.CreateBitmap()
bmp.CreateCompatibleBitmap(src_dc, width, height)
mem_dc.SelectObject(bmp)
mem_dc.BitBlt((0, 0), (width, height), src_dc, (offset_x, offset_y), win32con.SRCCOPY)

signed_ints = bmp.GetBitmapBits(True)
win32gui.DeleteObject(bmp.GetHandle())
bmp_array = np.frombuffer(signed_ints, dtype=np.uint8)
bmp_array.shape = (height, width, 4)
rgb_array = np.delete(bmp_array, 3, 2)

mem_dc.DeleteDC()
src_dc.DeleteDC()
win32gui.ReleaseDC(hwnd, win_dc)

cv2.imwrite("screenshot.png", rgb_array)
```

**Debug Log**

I couldn't find any suspicious signs.

**To Reproduce**

1. Connect PS5 on chiaki-ng
2. Run above python program
3. or Run OBS and capture "chiaki-ng" window

Note: If you screenshot first, you may get it right. However, if you do it several times, it will go wrong.

**Expected behavior**

Take screenshots correctly from other applications.

**Screenshots**

on chiaki-ng
![screenshot_chiaki-ng](https://github.com/user-attachments/assets/d7777a2c-ee19-4d7f-b4ad-61ecac6f3735)

on original Chiaki
![screenshot_original_chiaki](https://github.com/user-attachments/assets/fbac08b0-eac1-4ef9-a66a-ddf0fe69ed33)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11 Pro 23H2
 - Device: Core i5-12600KF & GeForce GTX 1660
 - chiaki-ng Version: v1.8.0

**Additional context**

**Comment by streetpea** [comment]
@jbaiter @nowrep do you have any idea about this?

**Comment by jbaiter** [comment]
Original Chiaki used OpenGL, chiaki-ng uses Vulkan, that might have something to do with it 🤔

Maybe related: https://obsproject.com/forum/threads/vulkan-cant-be-captured-in-windows-10.163768/

**Comment by nowrep** [comment]
Works just fine here on Linux with https://github.com/nowrep/obs-vkcapture  
If obs on windows can't capture the window you should open issue with them.

**Comment by akaymd** [comment]
Thanks for the response.

I was able to capture it with game capture on OBS.
And Also able to capture from other programs by using  [Windows.Graphics.Capture](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture?view=winrt-26100) of WinRT instead of the Win32API BitBlt.

This issue has been resolved.
Thank you.
