### ISSUE TITLE
[BUG] ROG Ally When pressing the 'B' button on the controller, it actually responds as the PS button.

### ISSUE THREAD

**Issue by pcccccc** [streetpea/chiaki-ng#387]
**Describe the bug**
Hello, thank you very much for your open-source project! I am using Chiaki-ng very smoothly on the Steam Deck, but I encountered a small issue on the Rog Ally (Windows).
ROG Ally When pressing the 'B' button on the controller, it actually responds as the PS button.

**Debug Log**
nothing

**To Reproduce**
1. Connect Playstation 5
2. push B button

**Screenshots**
https://github.com/user-attachments/assets/fb825899-f8d7-4d6c-afc6-602ad08c782e

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2
 - Device Rog Ally 
 - chiaki-ng Version : 1.8.1

**Comment by streetpea** [comment]
It sounds like you have escape mapped to the b button (maybe in handheld companion) ... the home button is mapped to esc ... please map escape to a different button for it to work correctly

**Comment by pcccccc** [comment]
okay my bad
