### ISSUE TITLE
[BUG] PS5 doesn't appear in device list

### ISSUE THREAD

**Issue by nicolaspaulson** [streetpea/chiaki-ng#397]
**Describe the bug**
Since updating to chiaki-ng (1.8.1) my PS5 can no longer be found in the device list. I have verified that the PS5 and my Steam Deck are on the same network. I've deleted my registered console and registered it manually again (had troubles with connecting with that too) and still can't find the PS5 in the device list.

**Debug Log**
None

**To Reproduce**
1. Open chiaki-ng
2. Have a registered PS5 in sleep mode
3. Observe that PS5 does not appear in the device list
4. Restart PS5, restart Steam Deck, open chiaki-ng again and observe still no PS5

**Expected behavior**
Registered PS5 console should appear in the device list for me to wake from sleep.

**Screenshots**
Unnecessary.

**Desktop (please complete the following information):**
 - OS: SteamOS
 - Version: 3.7 build 20240827.1001 (I know this is SteamOS dev build but I haven't had any issues until chiaki-ng)
 - Device: Steam Deck
 - chiaki-ng Version: 1.8.1

**Additional context**
Not needed.

**Comment by nthrow** [comment]
Having the same issue on chiaki-ng 1.8.1 on a SteamDeck OLED running SteamOS 3.5.19 build 20270422.1.  Purged and reinstalled Chiaki, reregistered console, got it to work again briefly then the next time I opened the app the console was gone again.  I see the PS5 in Settings > Consoles > Registered Consoles, but its not available for launch in the main menu, and selecting "Auto-Connect" in the settings and then closing and reopening the app just hangs on "waiting for console".  My PS5 is at the latest system OS version and is using a static IP address.

**Comment by streetpea** [comment]
Have you tried manually adding via ip?

**Comment by nthrow** [comment]
Yes, it brings me to a register console page again as if the previous device isn't acknowledged in the settings.  I've deleted and re-registered the console now multiple times just to have the issue recur.  I'm currently downgrading to 1.7.4 and will report back if the issue persists.

**Comment by streetpea** [comment]
so it looks like I have 2 issues to look at then :)

**Comment by nicolaspaulson** [comment]
@streetpea I did manually add via IP with the console ready and awake and it still didn't appear in the list. I did downgrade from main to beta branch (3.7 -> 3.6.9 steamOS) and I am able to find my PS5 in the device list.

**Comment by streetpea** [comment]
@nicolaspaulson @nthrow can you try this build: https://github.com/streetpea/chiaki-ng/actions/runs/10648123281/artifacts/1878278621 and see if it fixes your issue?

You can first unzip it to your downloads folder and then make it executable with:
```
chmod +x ~/Downloads/chiaki-ng.Appimage
```
and then open it with:
```
~/Downloads/chiaki-ng.Appimage
```
Then, close it and you can copy settings from the flatpak with
```
cp ~/.var/app/io.github.streetpea.Chiaki4deck/config/Chiaki/Chiaki.conf ~/.config/Chiaki/Chiaki.conf
```
and then you can reopen the appimage and use it to test it out.

**Comment by streetpea** [comment]
Manual registration is working fine for me on 1.8.1. Are you making sure to select PS5 as console type? Can you open chiaki-ng from the konsole using:
```
flatpak run io.github.streetpea.Chiaki4deck
```
and post the output when you try to register?

**Comment by nicolaspaulson** [comment]
@streetpea manual registration works some of the time for me on 1.8.1 but once registered I still wouldn't see the PS5. I can go back to the main branch of SteamOS tomorrow and try the patch you sent

**Comment by nicolaspaulson** [comment]
@streetpea I finally tried this out on the 3.7 main branch of Steam OS and am still unable to find the PS5 in the device list

**Comment by nicolaspaulson** [comment]
@streetpea I also installed 1.7.4 Chiaki4deck which was previously working for me but it also doesn't work on 3.7 main branch of SteamOS.

**Comment by streetpea** [comment]
In that case it seems broadcast is broken for you on that branch. It works fine for me on main though.

**Comment by streetpea** [comment]
@nicolaspaulson can you post the output of:
```
ip addr show
```
In the konsole?

**Comment by nicolaspaulson** [comment]
@streetpea after opening chiaki-ng via konsole? or just with a fresh konsole?

**Comment by streetpea** [comment]
@nicolaspaulson can you try this build please https://github.com/streetpea/chiaki-ng/actions/runs/10725775802/artifacts/1897762119 and post verbose logs? it should post more logs about discovery.

**Comment by streetpea** [comment]
@nicolaspaulson from your logs discovery is sending properly to your only configured broadcast address as configured on your Steam Deck (shown by ip addr show). In other words it is working correctly. What is the private ip for your PlayStation (not sensitive as it’s specific to your network).

**Comment by nicolaspaulson** [comment]
@streetpea 192.128.1.20

**Comment by streetpea** [comment]
It should be on that network then as chiaki-ng is sending a broadcast request to 192.168.1.255. For some reason your router isn’t sending the broadcast to your ps5 when sent from your Steam Deck

**Comment by nicolaspaulson** [comment]
@streetpea thank you for your help in debugging. I have IPv4 enabled on my steam deck and IPv6 disabled on my router. Not sure what the deal is but happy to know it's not chiaki-ng

**Comment by nicolaspaulson** [comment]
on a quick side note: I can connect to my PS5 using the automation script

**Comment by streetpea** [comment]
You can connect fine using the automation bc it’s directly using the ip vs needing to rely on broadcast to discover the console locally

**Comment by streetpea** [comment]
@nicolaspaulson my suggestion is to use a manually added connection using your previously registered console instead of registering on the first connection. This is enabled (changed from needing to discover the console to just needing to have it registered) in this build: https://github.com/streetpea/chiaki-ng/actions/runs/10730001840/artifacts/1898981012. Please try it out and see if you able to successfully add your console via ip and choosing your registered console.

**Comment by nicolaspaulson** [comment]
@streetpea just gave that build a try. My console is already registered and I tried adding it manually via IP and selecting the registered console in the drop down but I'm not finding it.

**Comment by streetpea** [comment]
@nicolaspaulson just to confirm when you open the add a console page which initial option is selected?

**Comment by nicolaspaulson** [comment]
When I open the add a console page the title is Add Manual Console, Host is empty and Registered Consoles defaults to "Select an Option". 

My console is indeed listed under the registered hosts like you posted.

**Comment by streetpea** [comment]
@nicolaspaulson i think I misunderstood you then. So you’re saying after adding the console it’s not showing up in the ui then?

**Comment by nicolaspaulson** [comment]
@streetpea yeah it's not appearing in the UI

**Comment by streetpea** [comment]
You are clicking the + button and it’s not appearing there when you select the dropdown that initially lists select and option?

**Comment by nicolaspaulson** [comment]
It appears there, it doesn't appear in the main screen UI

**Comment by streetpea** [comment]
I see that's weird it shows up fine for me when you
```
cat ~/.config/Chiaki/Chiaki.conf
```
Do you see manual_hosts like:
```
[manual_hosts]
1\host=192.168.1.16
1\id=1
1\registered=true
1\registered_mac=@ByteArray...)
size=1
```
or specifically what do you see ... you can just comment out the mac (ip is fine since private anyway in this case)

**Comment by nicolaspaulson** [comment]
```
[manual_hosts]
1\host=192.168.1.208
1\id=1
1\registered=true
1\registered_mac=@ByteArray(...)
size=0
```
I just got a new router today which is why the IP address is different than I've posted before

**Comment by nicolaspaulson** [comment]
@streetpea I manually changed the config to `size=1` and I'm seeing the PS5 in the main UI now, though I see two copies, one discovered in standby state and one manual in ready state

**Comment by streetpea** [comment]
@nicolaspaulson it should be fixed in this build https://github.com/streetpea/chiaki-ng/actions/runs/10746845200/artifacts/1903558600 you can try deleting and re-adding the console to test.

**Comment by streetpea** [comment]
Also the console shows up once as a manual console where you can manage the console and use it without needing discovery. It also shows up via manual discovery which allows you to see the current console state and use the auto-connect feature you can select from the consoles menu in the settings.

**Comment by nicolaspaulson** [comment]
@streetpea thanks again for all your help with this. The latest build you attached worked for me and I successfully added my console again after deleting it. The manual listing on the UI does not show the correct state, the `discovered` list option shows my console in standby state correctly, while the manual list option shows it in a ready state. Either way, it's fixed for me now and I appreciate all your time.

**Comment by streetpea** [comment]
@nicolaspaulson this build https://github.com/streetpea/chiaki-ng/actions/runs/10747851962/artifacts/1903774814 consolidates the view for manual consoles that are discovered into one discovered + manual pane with all relevant options.

**Comment by nicolaspaulson** [comment]
@streetpea works like a charm

**Comment by streetpea** [comment]
@nicolaspaulson since the console can’t be discovered via broadcast due to a network problem and instead can be manually registered to appear appropriately using manual discovery can we close this issue? Or is there something else you would like me to address for this issue?

**Comment by nicolaspaulson** [comment]
@streetpea we can close it. I am curious why my config had `size=0` and why changing it to `size=1` made my console appear but thanks for your help

**Comment by streetpea** [comment]
@nicolaspaulson it worked bc that manual host was leftover from when you had one before it was removed. When the array is removed the size changes but the old entry isn’t deleted in the settings file until a new entry that uses that index is created (it’s basically just ignored until that point). What you did was re-enable that deleted console that had been completely removed from the settings file yet.
