### ISSUE TITLE
Chiaki-ng doesn't open in 1.8.1

### ISSUE THREAD

**Issue by isaias012-sys** [streetpea/chiaki-ng#398]
Hello, i'm asking this because, is the first time i'm using this software and when i wanna open, the program doesn't open.

**Comment by superboiwonder** [comment]
Im having a similar issue and have tried multiple versions up to the latest one
![image_2024-09-04_190143698](https://github.com/user-attachments/assets/da67d09d-79cf-4b90-8e32-dc6f449dce17)

**Comment by streetpea** [comment]
Do you happen to have the OpenGL, OpenGL, Vulkan compatibility pack installed? If so please uninstall.

**Comment by superboiwonder** [comment]
where do I find that?

**Comment by streetpea** [comment]
See https://www.reddit.com/r/ROGAlly/s/0PfARk5KM6

**Comment by superboiwonder** [comment]
Not finding it anywhere in installed apps or system components. Also....
![Screenshot (2)](https://github.com/user-attachments/assets/7ffb9f12-32dc-47ad-a89d-14589d23c9a4)
![{9E1FC066-B273-4446-8768-489E5D19002C}](https://github.com/user-attachments/assets/e92f3df2-2ced-4233-84fe-ad369d6786db)

**Comment by superboiwonder** [comment]
Hold on thats not the screenshot i took fot the 1st one

**Comment by superboiwonder** [comment]
![{AECB7488-D5DA-40CA-B9A8-F246096A447A}](https://github.com/user-attachments/assets/27555fc5-d5a4-461f-8012-792911ac92d2)

**Comment by streetpea** [comment]
It should be under installed programs I believe. Can you post the output from debug view  you try opening the app with debug view open? Debug view can be installed here https://download.sysinternals.com/files/DebugView.zip

**Comment by superboiwonder** [comment]
[Chiaki Debug.LOG](https://github.com/user-attachments/files/16882305/Chiaki.Debug.LOG)

**Comment by streetpea** [comment]
@superboiwonder please update your graphics card driver. The version of Vulkan you are using (1.1.0) is too old for libplacebo which makes it too old for running Chiaki-ng (which uses libplacebo as the renderer)

**Comment by superboiwonder** [comment]
Im on the latest available for this pc despite saying update required

**Comment by streetpea** [comment]
Then your body processor is incompatible with chiaki-ng

**Comment by streetpea** [comment]
@superboiwonder please see Chiaki https://git.sr.ht/~thestr4ng3r/chiaki which includes support for legacy devices.

**Comment by superboiwonder** [comment]
Okay I was wondering why I could get it to launch on my tower but not here. My ally (Z1E) runs it pretty well just stutters some times on there. TBH I prefer your app over Sony's any day and definitely appreciate your work.

**Comment by streetpea** [comment]
@isaias012-sys cab you provide more information on your os, etc?

**Comment by streetpea** [comment]
@rodrigoxp208 it looks like you’re not picking up the qml dir.

**Comment by streetpea** [comment]
@superboiwonder actually you can also install the Vulkan runtime manually instead of using the ones provided with your driver. You should be able to get a version compatible with chiaki-ng by downloading the latest runtime via https://sdk.lunarg.com/sdk/download/1.3.296.0/windows/VulkanRT-1.3.296.0-Installer.exe
