### ISSUE TITLE
[BUG] Video not updating after awaking from screen lock

### ISSUE THREAD

**Issue by Aetf** [streetpea/chiaki-ng#400]
**Describe the bug**
When streaming with Chiaki-ng from my PS5, I left the system for a while and the system entered lock screen (as configured by the KDE desktop).

After unlocking and reentering the system, chiaki-ng stopped updating video frames. The screen was frozen at the last frame. The game is still controllable and from the audio I can hear that my operations still worked, just the frame wasn't updated.

**Debug Log**

[chiaki_session_2024-09-04_23-02-50-873873.log](https://github.com/user-attachments/files/16884677/chiaki_session_2024-09-04_23-02-50-873873.log)

**To Reproduce**
1. Start streaming
2. Lock screen
3. Unlock screen

**Expected behavior**
Streaming continues to work as normal after unlocking. And chiaki-ng should inhibit sleep/locking while streaming.

**Desktop (please complete the following information):**
 - OS: Archlinux + KDE Wayland
 - Version: `Linux Aetf-Arch-XPS 6.9.7-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:27 +0000 x86_64 GNU/Linux`
 - KDE Version `6.1`
 - Device: desktop PC
 - chiaki-ng Version: 1.8.1

**Additional context**

chiaki-ng can only be SIGKILLed after the error.

**Comment by Aetf** [comment]
I should add that the screen locked even when I'm actively playing. Seems like the controller input isn't considered by KDE as active use. This makes it more important for chiaki-ng to inhibit sleep...

**Comment by streetpea** [comment]
@Aetf what do you selected in the settings for action on suspend?

**Comment by Aetf** [comment]
Interesting. I used the locally compiled version built from a clean chroot (from [AUR](https://aur.archlinux.org/packages/chiaki-ng)). From the code, system inhibition is guarded by `CHIAKI_HAVE_DBUS`. Maybe it's caused by the dbus dependency missing during compilation. Let me play with the PKGBUILD for a bit.

As for ctrl+q, it doesn't work. The mouse did pop out (which was hidden automatically when starting streaming), but the confirmation dialog (when configured to ask) didn't show up. And it's the same when configured to do nothing on disconnect: mouse popped out, can't click anything.

**Comment by streetpea** [comment]
@Aetf one way to check is download the flatpak for testing purposes. See if it works. If it does, then you know something is going on with the arch build.

**Comment by Aetf** [comment]
Just tried the flatpak version. It also doesn't inhibit sleep.

**Comment by streetpea** [comment]
Can you post the logs running from konsole?

**Comment by Aetf** [comment]
https://gist.github.com/Aetf/d5c840919501954110aeec3482ee30c3

**Comment by streetpea** [comment]
@Aetf the log you linked seems fine. Can you post the logs from the konsole if you launch via the konsole?

**Comment by Aetf** [comment]
running flatpak version from konsole and tried lock screen while streaming. This time it actually works.
So the graphics freezing issue might be due to different dependency version used for compiling.

However I think the sleep inhibit still isn't quite right.

konsole log: https://gist.github.com/Aetf/646a9d5833167f686dae6eaf50b216a3

Using dbus-monitor to see dbus message exchanges, and indeed chiaki is calling the inhibit API
```
method call time=1725584174.295683 sender=:1.1001 -> destination=org.freedesktop.login1 serial=7 path=/org/freedesktop/login1; interface=org.freedesktop.login1.Manager; member=Inhibit
   string "sleep"
   string "Chiaki"
   string "Remote Play session"
   string "delay"
signal time=1725584174.306961 sender=:1.6 -> destination=(null destination) serial=4278 path=/org/freedesktop/login1; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "org.freedesktop.login1.Manager"
   array [
      dict entry(
         string "DelayInhibited"
         variant             string "sleep"
      )
   ]
   array [
   ]
method call time=1725584183.035312 sender=:1.1002 -> destination=org.freedesktop.login1 serial=2 path=/org/freedesktop/login1; interface=org.freedesktop.login1.Manager; member=ListInhibitors
```

`systemd-inhibit` shows that it is registered.
```
❯ systemd-inhibit
WHO                    UID  USER PID    COMM            WHAT                                                                       WHY                                                       >
NetworkManager         0    root 2196   NetworkManager  sleep                                                                      NetworkManager needs to turn off networks                 >
UPower                 0    root 3119   upowerd         sleep                                                                      Pause device polling                                      >
net.reactivated.Fprint 0    root 646445 fprintd         sleep                                                                      Suspend fingerprint readers                               >
Chiaki                 1000 aetf 646649 xdg-dbus-proxy  sleep                                                                      Remote Play session                                       >
PowerDevil             1000 aetf 191552 org_kde_powerde handle-power-key:handle-suspend-key:handle-hibernate-key:handle-lid-switch KDE handles power events                                  >
Screen Locker          1000 aetf 2595   kwin_wayland    sleep                                                                      Ensuring that the screen gets locked before going to sleep>

6 inhibitors listed.
```

However, it is not shown in the KDE PowerDevil plasmoid: 
![image](https://github.com/user-attachments/assets/db840c3a-2f21-490f-9121-0cf7880aaa25)
 
For comparison, this is what it should look like, when I manually inhibit sleep (note the mode I used is `block` rather than `delay` in [code](https://github.com/streetpea/chiaki-ng/blob/4311516718dd41f3c416029ece2ad4eb2cb82c2d/gui/src/qmlbackend.cpp#L188)):
```
> systemd-inhibit --who="test" --what="sleep" --mode="block" --why="test" sleep infinity
```

![image](https://github.com/user-attachments/assets/7cebc5a6-e26e-4618-a6dc-ceb881e50fbb)

**Comment by streetpea** [comment]
@Aetf please copy and paste the output from the konsole not the log file. You can save it as a file if you want. The thing is you can’t see sleep inhibited bc each connection is a separate session. You will only see it if you use the log from the konsole.

**Comment by Aetf** [comment]
I'm not sure I follow what you mean. I'm copy pasting the output from the terminal. That is the full output I pasted.

> The thing is you can’t see sleep inhibited bc each connection is a separate session. 

Not sure what you mean by each connection... I'm on running chiaki on a desktop Linux PC. There is no SteamDeck involved, if that was not clear before.


Anyway, here's the terminal output after I enabled `log_verbose=true` in config: https://gist.github.com/Aetf/3074ab4981598f566bd5e84eac66bc79


Reading the [doc](https://man.archlinux.org/man/core/systemd/systemd-inhibit.1.en) about inhibition, I now believe that `block` mode is more appropriate since the default timeout for `delay` is 5s ([source](https://man.archlinux.org/man/logind.conf.5.en#:~:text=InhibitDelayMaxSec)). Also, the inhibition should be for both `sleep` and `idle`, because the system can still lock the screen if only sleep is inhibited.

**Comment by streetpea** [comment]
@Aetf in that case sleep is not being inhibited you would see 2 separate sessions in the logs (the session is quit before sleeping and a new session is created after sleeping).

**Comment by streetpea** [comment]
@Aetf I reread your comments and I believe I originally misunderstood what you were asking for. Currently chiaki-ng just impedes sleep so that it can close down and then restart once sleep ends. Many users want to sleep. They just want the session to pick up after sleep. This is the functionality in chiaki-ng. As for the Lock Screen I don’t believe that needs to be impeded. Shouldn’t the app just continue running even with the Lock Screen up. At least that’s what I’ve observed running chiaki-ng on Manjaro natively as well as with the flatpak

**Comment by streetpea** [comment]
@Aetf just a heads up btw you should install pipewire-pulse as opposed to pulse audio to get working haptics with the dualsense if you want that.

**Comment by Aetf** [comment]
I care about lock screen because even when I'm actively playing, the lock screen shows up and interrupts the session. I have to manually move the mouse every once a while to reset the timer. I can manually enable the keep awake function before playing, but that's just annoying.

As for pipewire-pulse, I have long migrated to pipewire and have pipewire-pulse installed. Not sure why that warning is still there. I do have working haptics with the dualsense though.

**Comment by streetpea** [comment]
@Aetf when I tested on Manjaro as well as SteamOS (both based from Arch Linux) the lock screen does not prevent chiaki-ng from continuing to play. Do you have a setting set that causes programs to suspend when the lock screen is activated?

**Comment by Aetf** [comment]
Hmm, how could a lock screen not prevent chiaki-ng from playing? When it shows up, the full desktop is covered by the lock screen, and I need to unlock it to see my desktop, including chiaki-ng.

Here are my lock screen settings 

![image](https://github.com/user-attachments/assets/b3f7119f-0be3-43c0-b6ae-7eacd2ab2938)


> running via Steam prevents auto-locking if you have controller input for arch.

I haven't tried that. Let me see if it works.

**Comment by streetpea** [comment]
@aetf no image is displayed but the app continues running until I open the Lock Screen and then am able to resume playing.

**Comment by streetpea** [comment]
@Aetf did launching via steam fix your problem with gamepad input not preventing the KDE lock screen from appearing?

**Comment by Aetf** [comment]
Sorry for the late reply. Yeah launching via steam indeed fixes the problem.

**Comment by streetpea** [comment]
@Aetf is it ok if I close this then
