### ISSUE TITLE
Idk if the Dualsense Speaker is supported but I am struggling to find any lil bit of info on it. 

### ISSUE THREAD

**Issue by BoxIsMyNamee** [streetpea/chiaki-ng#402]
I am playing ASTRO BOT on my (docked) Steam Deck with a WIRED Dualsense controller & Steam input turned off. Gyro, Adaptive Triggers & Rumble are all amazing. But my controllers speaker is outputting nothing. No sound whatsoever. It should play the environment sounds i’m in (ie, grass, water)

Am I just dumb and missing something totally obvious. Is it just entirely impossible??

**Comment by BoxIsMyNamee** [comment]
i have tested 2 controllers and both had no idea but had audio on console.

**Comment by streetpea** [comment]
The DualSense speaker is not supported by remote play .. the data is not being sent by Sony so can’t implemented.
