### ISSUE TITLE
cut the video and audio 

### ISSUE THREAD

**Issue by Mdpt1995** [streetpea/chiaki-ng#412]
Good evening, I would like to cut the video and audio input, leaving only the control input.
and to be able to use a xim apex adapter because the chiaki version has a lot of delay, if it is possible to remove the video and audio net, I would be very happy to contribute

**Comment by streetpea** [comment]
No there isn’t and please stop opening issues. As I already said look at #405 where this question was asked.

**Comment by streetpea** [comment]
@Mdpt1995 given those consoles aren’t registered you can hide them as of Chiaki v1.9.0
