### ISSUE TITLE
Add `chiaki-ng` cask to Homebrew

### ISSUE THREAD

**Issue by Tokarak** [streetpea/chiaki-ng#416]
For the unaware, Homebrew is a package manager for MacOS: https://brew.sh.
I think this project is perfectly suitable as a homebrew cask. "chiaki" is already a cask. There are currently no issues or prs to add chiaki-ng as a cask here or in Homebrew. I'm only starting to use this project, so I'm not ready to open a pr to homebrew yet.

Kinda low priority; anyone is welcome to pick this up.

**Comment by streetpea** [comment]
Seems pretty simple from the Chiaki cask (they just download the executable from the releases page) … I can put it in a similar request for chiaki-ng

**Comment by streetpea** [comment]
@Tokarak it says they frown on others recommending their own work unless it is very popular so I probably shouldn’t submit on second thought.

**Comment by streetpea** [comment]
@Tokarak I created a cask file for chiaki-ng here: https://github.com/streetpea/chiaki-ng/blob/main/scripts/chiaki-ng.rb but it currently fails audit (`brew audit --new --cask chiaki-ng`) with:

```
==> Downloading and extracting artifacts
==> Downloading https://github.com/streetpea/chiaki-ng/releases/download/v1.9.0/
Already downloaded: /Users/siler23/Library/Caches/Homebrew/downloads/6cd1c92e8e7d6d5fb4f73a9b579b97473153e8bcc9966be0ad785d828a3a926b--chiaki-ng-macos_amd64-Release.zip
==> Downloading https://github.com/streetpea/chiaki-ng/releases/download/v1.9.0/
Already downloaded: /Users/siler23/Library/Caches/Homebrew/downloads/6cd1c92e8e7d6d5fb4f73a9b579b97473153e8bcc9966be0ad785d828a3a926b--chiaki-ng-macos_amd64-Release.zip
audit for chiaki-ng: failed
 - Signature verification failed:
/private/tmp/cask-audit20241001-15821-2wx2b6/chiaki-ng.app: rejected

macOS on ARM requires software to be signed.
Please contact the upstream developer to let them know they should sign and notarize their software.
chiaki-ng
  * line 8, col 2: Signature verification failed:
    /private/tmp/cask-audit20241001-15821-2wx2b6/chiaki-ng.app: rejected
    
    macOS on ARM requires software to be signed.
    Please contact the upstream developer to let them know they should sign and notarize their software.
Error: 1 problem in 1 cask detected.
```

It currently uses self-signing so it can be run on arm Macs but you have to bypass a warning that it's not signed by a verified developer since it doesn't use an Apple developer certificate. The reason why it doesn't is because an Apple certificate costs $100/year which doesn't really make sense for a free open source app. Due to this, it may not be possible to publish as a cask.

**Comment by Tokarak** [comment]
Thanks for the cask. That problem surely can't be right, there must be some self-signed apps on homebrew. I also remember downloading a cask that was literally quarantined. I don't have time to look into this Right Now.

**Comment by streetpea** [comment]
@Tokarak you can use the url with brew install --cask to install by yourself. It seems it’s a requirement for new casks. Maybe it was an old cask that was grandfathered in.

**Comment by streetpea** [comment]
@Tokarak I made a pull request here https://github.com/Homebrew/homebrew-cask/pull/187206 but not sure if it will be accepted due to the aforementioned issue.

**Comment by streetpea** [comment]
@Tokarak see https://github.com/Homebrew/homebrew-cask/pull/187206. It seems like unless we implement code-signing adding to homebrew cask doesn't make sense. We could add a tap you can install from instead and then you would just install and be able to update. I think that makes the most sense for this issue. I'll go ahead and create a tap for chiaki-ng cask I created and users can install from there.

**Comment by streetpea** [comment]
@Tokarak I created my own tap for `chiaki-ng` you can now install with:
```
brew install --cask streetpea/streetpea/chiaki-ng
```
I also updated the releases page https://github.com/streetpea/chiaki-ng/releases/tag/v1.9.0 to mention the tap for MacOS users wanting to easily update their release without downloading from GitHub.

**Comment by federicoiosue** [comment]
Hi @streetpea, thanks for the great piece of software you work on!

At the moment looking at logs the Homebrew tap has a couple of problems:

- Ruby script uses a couple of deprecated stuff
- The version is an old one, the latest 1.10 is not available

```shell
brew info --cask streetpea/streetpea/chiaki-ng

Warning: Calling the `verified` parameter in the `url` stanza is deprecated! Use the default URL verification behaviour instead.
Please report this issue to the streetpea/homebrew-streetpea tap (not Homebrew/* repositories), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/streetpea/homebrew-streetpea/Casks/chiaki-ng.rb:8

Warning: Calling `postflight` is deprecated! Use `postflight_steps` instead.
Please report this issue to the streetpea/homebrew-streetpea tap (not Homebrew/* repositories), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/streetpea/homebrew-streetpea/Casks/chiaki-ng.rb:20

==> chiaki-ng ✔ (chiaki-ng): 1.9.9,2
PlayStation remote play client next-generation
https://streetpea.github.io/chiaki-ng/
Installed (on request)
/opt/homebrew/Caskroom/chiaki-ng/1.9.9,2 (422.5MB)
  Installed on 2024-12-26 at 21:43:31
From: https://github.com/streetpea/homebrew-streetpea/blob/HEAD/Casks/chiaki-ng.rb
==> Artifacts
chiaki-ng.app (App)
```
