### ISSUE TITLE
Request to display the name of the launched shortcut on the title of the Windows version.

### ISSUE THREAD

**Issue by x62915** [streetpea/chiaki-ng#419]
For example, at startup, display the variable name "user1" from "-- profile=user1" in the Windows program title.
![4](https://github.com/user-attachments/assets/5a25889d-ab9a-4afd-8ba2-f6452bdbe594)

**Before**
![1](https://github.com/user-attachments/assets/3273c1d6-4cf2-42f6-9001-468a26047923)

**After**
![3](https://github.com/user-attachments/assets/f2eef2d8-f85c-4ad0-a0b2-c54ad83e9140)
or
![2](https://github.com/user-attachments/assets/b1f3c249-8310-474c-8586-8a92fe2c87ee)

**Comment by streetpea** [comment]
You can always the current profile in the config section of the settings.

**Comment by x62915** [comment]
When multiple windows are launched and applications are running on the same computer, it is difficult to visually distinguish the devices corresponding to the windows.
Or could you please write a detailed build process for the Windows platform.

**Comment by x62915** [comment]
Although my request was not fulfilled, I still greatly appreciate your efforts.

**Comment by streetpea** [comment]
I didn’t say I wouldn’t fulfill it, just stating what is available now. I have to look into it, I think it may be pretty simple so I can definitely look into it

**Comment by x62915** [comment]
Your reply has made me very happy, and I would like to express my gratitude again for your efforts

**Comment by streetpea** [comment]
done it will be in next release .. if you would like I can build you a version from the latest commit with this change now just lmk @x62915.

**Comment by x62915** [comment]
Of course, I would be happy to. Where can I obtain this version

**Comment by streetpea** [comment]
@x62915 https://github.com/streetpea/chiaki-ng/actions/runs/11078154932/artifacts/1989517243

**Comment by x62915** [comment]
Thank you.
(╬▔▽▔)凸
