### ISSUE TITLE
Add support for using the touchscreen with the touchpad

### ISSUE THREAD

**Issue by bdr27** [streetpea/chiaki-ng#422]
Had a look around the windows version and I'm pretty sure the original Chiaki had support to emulate the touchpad with the touch screen. This would be handy for devices like ROG Ally, Ayaneo ect as there's no easy way to remap the touchpad button on them. Maybe I'm missing the setting in the menu but it doesn't seem to be an option

**Comment by streetpea** [comment]
@bdr27 The original Chiaki doesn’t have support for this. Chiaki-ng does have support for this. It just works out of the box. No setting is needed.
