### ISSUE TITLE
There's no download for chiaki.nro

### ISSUE THREAD

**Issue by rokavii** [streetpea/chiaki-ng#423]
do i have to compile it? both chiaki links say to download a file that isnt there, and i can't find it in any of the folders. the last time i compiled something, or tried to, it didnt even work. 

why put a method saying to "download the .nro" that Is Not There?

**Comment by streetpea** [comment]
There is no nro for Chiaki-ng. See https://github.com/streetpea/chiaki-ng/issues/355 already tracking if someone with a modded switch is willing to make a release since I don’t have one.
