### ISSUE TITLE
Chiaki is isn't working on my firewall

### ISSUE THREAD

**Issue by screw1logic** [streetpea/chiaki-ng#428]
I'm currently on linux and I'm using ufw firewall. So what ports and stuff does Chiaki need to work.

**Comment by streetpea** [comment]
It uses random internal ports on the given pc. It connects to port 9295, 9296, and 9297 on the ps console for local connection.

**Comment by screw1logic** [comment]
For anyone who has the same issue as me and doesn't under stand what streeptpea said here is what worked.
sudo ufw allow from 192.168.0.0/16
sudo ufw allow 9297
sudo ufw allow 9296
sudo ufw allow 9295
