### ISSUE TITLE
[BUG] MacOS 15 build from source crash

### ISSUE THREAD

**Issue by kevinmore** [streetpea/chiaki-ng#430]
**Describe the bug**
Hi,

Newbee here. I'm trying to build `chiaki-ng` from source and try to understand the code logic.
My current setup is a Macbook Pro M3, with MacOS 15.0.1.
The build is sucessful, but when running it, it crashes. Seems to be an issue related to Vulkan, which I don't know how to resolve. The crash line is here: https://github.com/streetpea/chiaki-ng/blob/main/gui/src/qmlmainwindow.cpp#L395

Please see the log below. And the root CMake file attached. Much appreiated for any help!

[CMakeLists.txt](https://github.com/user-attachments/files/17293712/CMakeLists.txt)

**Debug Log**

```
chiaki.gui: [libplacebo] Initialized libplacebo v7.349.0 (API v349)
chiaki.gui: [libplacebo] Creating vulkan instance with extensions:
chiaki.gui: [libplacebo]     VK_KHR_get_physical_device_properties2
chiaki.gui: [libplacebo]     VK_KHR_portability_enumeration
chiaki.gui: [libplacebo]     VK_EXT_metal_surface
chiaki.gui: [libplacebo]     VK_KHR_surface
chiaki.gui: [libplacebo] Failed creating instance: VK_ERROR_INCOMPATIBLE_DRIVER
chiaki.gui: [libplacebo] Failed initializing vulkan instance

Process finished with exit code 139 (interrupted by signal 11:SIGSEGV)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. SteamOS]
 - Device [e.g. Steam Deck]
 - chiaki-ng Version [e.g. 1.6.2]

**Additional context**

**Comment by streetpea** [comment]
@kevinmore make sure you create the package following the steps outlined here to create an executable application package on macOS https://github.com/streetpea/chiaki-ng/blob/main/.github/workflows/build-macos-arm.yml. If you just want to build and run in the terminal make sure you have molten-vk installed for running (this is usually packaged with the app in the package step) which you can do with:
```
brew install molten-vk
```

**Comment by kevinmore** [comment]
Thanks for pointing out @streetpea,

After installing molten-vk, I can debug from my Mac. 

```
brew install molten-vk
```
Closing the issue now.
