### ISSUE TITLE
[BUG] Can't register PS5

### ISSUE THREAD

**Issue by schradert** [streetpea/chiaki-ng#432]
**Describe the bug**
chiaki-ng does not discover my console, and manually adding it gives me the error `[E] Regist failed to send search: Invalid argument` despite the relevant Power Saving features being enabled.

For the manual connection:
1. the local IP address for `Host` is correct. Both devices are currently wired on the same subnet, but on WiFi they can also reach each other without issue.
2. My base64 encoded account ID was entered automatically by the button that triggers the `psn-account-id` script.
3. My console account does not have a login PIN and the 8-digit Remote Play key was also entered correctly.

**Desktop (please complete the following information):**
- OS: NixOS [24.11.20241006.c31898a]
- Device: Steam Deck OLED 1TB
- chiaki-ng: v1.9.0

**Additional context**
I am using NixOS, so chiaki-ng was not installed through flatpak, but it was built from source according to this [derivation](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/chiaki-ng/default.nix). Nothing out of the ordinary there.

Running `chiaki discover --host <ps5_ip>` appears to correctly detect the console and show my PS5 to be in the `ready` state.

**Comment by streetpea** [comment]
@schradert can you please post a log from the terminal of what is displayed when launching the app via the terminal and it doesn't discover your console with verbose logging enabled. Same for registration that fails.

**Comment by schradert** [comment]
How do I do that? I don't see any documentation on verbose logging. `--help` and `--usage` don't list any relevant flags, options, or environment variables, and standard `-v` and `--verbose` didn't work.

**Comment by streetpea** [comment]
Go into settings (the gear icon) and check the box for verbose logging. They will then appear in the terminal if you launch via the terminal

**Comment by schradert** [comment]
@streetpea sorry for not responding here. I did get it working by manually connecting the device. Verbose logging didn't tell me anything obvious, but what I had to do differently was deselect "Broadcast", which was not included in the instructions. I didn't think to try that at first because I had zoom problems in desktop mode which was obscuring everything below the inputs lol, so I didn't even see it as an input on the console registration form. Anyways, appreciate your responsiveness. Still not sure about auto-discovery, but I don't care anymore since this is my only console.

**Comment by streetpea** [comment]
@schradert that makes since given the broadcast wasn’t working for you. Additionally, once manually registered discovery can be done via the manual ip instead of broadcast so autoconnect, seeing console state, etc. should still work.

**Comment by schradert** [comment]
Yep I can successfully wake and stream and suspend now, no problems. My controls aren't really working in games though so I need to figure that out, but that's a different issue than this thread.

**Comment by streetpea** [comment]
@schradert are you on the Steam Deck?

**Comment by schradert** [comment]
No I haven't created this launcher script yet to run it from steam. I've just been streaming straight from the chiaki-ng app in desktop mode.

**Comment by streetpea** [comment]
@schradert thats probably your issue. Desktop mode has its own controller config separate from game mode. Can you try adding a Steam shortcut via the button in the main menu and then try launching that via game mode?
