### ISSUE TITLE
More Apple platforms support

### ISSUE THREAD

**Issue by kevinmore** [streetpea/chiaki-ng#433]
Is there any plan to support more Apple platforms such as iOS and visionOS? If not, how should one implement such feature?

I'm trying to understand the repository, but it feels very difficult to do it as the lack of certain documentations and code comments. Could someone help me break down the code?

Thanks!

**Comment by streetpea** [comment]
See https://doc.qt.io/qt-6/ios.html for iOS to add iOS system calls via objective c to the qt code and then you would need to use separate qml layouts for iOS to fit properly on the screen in the gui/src/qml folder

**Comment by kevinmore** [comment]
Thanks @streetpea, but I think using Qt for an SwiftUI app has too much overhead. 

I just want to ask that - does all the beckend logic live in the `/lib` folder? And what does the `/lib/protobuf` do?

I'm thinking of building an iOS app from scratch, with only the essential Chiaki components.

**Comment by streetpea** [comment]
I was thinking it wouldn’t be a SwiftUI app it would be an objective c app

**Comment by streetpea** [comment]
The backend logic lives in the lib folder

**Comment by kevinmore** [comment]
@streetpea, I'm not sure. But WWDC23 has introduced a new way of interpolating Swift with C/C++, which looks promising.

See:
https://www.swift.org/documentation/cxx-interop/
https://developer.apple.com/wwdc23/10172

**Comment by streetpea** [comment]
I was thinking of skipping on swift and switfui entirely. Having said that, you could certainly rewrite the frontend code and gui for iOS and just link to the backend lib … In other words make a new folder for the iOS gui similar to android and switch

**Comment by kevinmore** [comment]
Closing it now because I decided to wrap the Chiaki lib into a swift package.

**Comment by iMonZ** [comment]
> Closing it now because I decided to wrap the Chiaki lib into a swift package and build an entire native swift app from scratch.

Wow thats awesome!
Do you have a work in progress repo?
Maybe we could help.

**Comment by kevinmore** [comment]
> > Closing it now because I decided to wrap the Chiaki lib into a swift package and build an entire native swift app from scratch.
> 
> Wow thats awesome! Do you have a work in progress repo? Maybe we could help.

No progress nor repo yet. Just finished the package and starting to build the app.

**Comment by kevinmore** [comment]
In case anyone is intereted in my progress. I've make a demo on visionOS, but I decided not to share to code. See video [here](https://youtu.be/Iy2F8tYwYfI).

**Comment by streetpea** [comment]
@kevinmore just a heads up but if you do decide to publish it you will need to share code with any users that want it per agpl3 which is an infectious license (if any code used in the project or linked to by the project is agpl3 then the whole project becomes infected with it and becomes agpl3.
