### ISSUE TITLE
[BUG]Chiaki stuttering after 20 minutes. Can someone help me download 1.6.1 on steam deck? I’m new to this 

### ISSUE THREAD

**Issue by 738273828** [streetpea/chiaki-ng#437]
[BUG]Chiaki stuttering after 20 minutes. Can someone help me download 1.6.1 on steam deck? I’m new to this

**Comment by streetpea** [comment]
You can do so following this https://docs.flathub.org/docs/for-users/downgrading/ but be advised that this will mean you are foregoing many bug fixes and improvements in the newer releases.

**Comment by 738273828** [comment]
> You can do so following this https://docs.flathub.org/docs/for-users/downgrading/ but be advised that this will mean you are foregoing many bug fixes and improvements in the newer releases.

How can I make it play full screen?

**Comment by 738273828** [comment]
> You can do so following this https://docs.flathub.org/docs/for-users/downgrading/ but be advised that this will mean you are foregoing many bug fixes and improvements in the newer releases.

I heard that this version doesn’t have problems with WiFi on Oled

**Comment by streetpea** [comment]
@738273828 I doubt that is the case. The oled wifi bug can be worked around by toggling on and off the wifi before starting the app or while it’s running

**Comment by 738273828** [comment]
> @738273828 I doubt that is the case. The oled wifi bug can be worked around by toggling on and off the wifi before starting the app or while it’s running

Do you also know a fix for the choppy static sound?

**Comment by streetpea** [comment]
@738273828 that also indicates a poor connection, likely the same fix. If you are still having issues you can increase the audio buffer in the audio/wifi tab of the settings but this will introduce lag to the audio so I would see if the WiFi trick of turning it off and on fixes this as well first.

**Comment by 738273828** [comment]
> @738273828 that also indicates a poor connection, likely the same fix. If you are still having issues you can increase the audio buffer in the audio/wifi tab of the settings but this will introduce lag to the audio so I would see if the WiFi trick of turning it off and on fixes this as well first.

Aw. The WiFi trick didn’t work.

**Comment by streetpea** [comment]
Then it's likely that your wifi has low stability (not low speed/throughout but low stability which really only matters for a few applications including game streaming. It doesn't matter for video streaming for example due to buffering.) Again 1.6.1 probably won't help but you can use the instructions I gave and try it out if you believe that will help you. It's just a few commands.
