### ISSUE TITLE
[BUG]Long Press not registering 

### ISSUE THREAD

**Issue by krozgrov** [streetpea/chiaki-ng#439]
I’m unsure whether this is a bug or a misconfiguration, but I wanted to start by asking here. I’m having an issue with Chiaki-NG on my Steam Deck where long presses aren’t being registered, particularly in Destiny 2. For example, when I try to long press the Left Bumper to perform the Warlock action of consuming a grenade to convert it into a turret, the action doesn’t trigger properly. Instead, my character just continues to hold the grenade.

However, when I pair my DualSense controller directly to the Steam Deck, the action works as expected. I’ve also tried adjusting the button settings from a regular press to a long press, but that hasn’t resolved the issue.

 - OS: SteamOS
 - Device Steam Deck
 - chiaki-ng Version 1.9.0

**Comment by streetpea** [comment]
chiaki-ng doesn’t do anything different for long presses from a Steam Deck controller vs a ps controller, the logic is exactly the same. It’s likely the difference is in the controller mapping in Steam (which is specific per controller) or a problem with the physical controller itself.

**Comment by krozgrov** [comment]
I'll try to reset the button mapping and try again.  Thanks @streetpea for following up.

**Comment by streetpea** [comment]
@krozgrov are you able to press your Steam Deck triggers all the way down? See https://www.reddit.com/r/SteamDeck/comments/11wgcbb/left_trigger_difficult_to_press_all_the_way/? Do you have another controller to try (maybe a generic/Xbox controller that is more closely aligned to the Steam Deck controller)

**Comment by krozgrov** [comment]
No matter how hard I press it doesn’t change the L1 behavior.  I did add fire end delay tried both 900ms and 500ms and still same issue.  Not sure I know what trigger settings you want me to post.  Thanks again for even entertaining this issue.

**Comment by streetpea** [comment]
@krozgrov was it the same DualSense controller? Can you disable steam input for the dualsense controller and see if there is any difference?

**Comment by krozgrov** [comment]
@streetpea  two different controllers.  Same issue with steam input, enabled or disabled.

**Comment by streetpea** [comment]
@krozgrov i misread read it as l2 and not l1. I’ll check l1 on my end.

**Comment by streetpea** [comment]
@krozgrov I tested it on my end and it looks like L1 is being sent properly. It's possible it's a bug with remote play with Destiny 2 itself. Can you test an L1 long press with Destiny 2 with the official remote play app?

**Comment by streetpea** [comment]
@krozgrov I tested it on my end and it looks like L1 is being sent properly. It's possible it's a bug with remote play with Destiny 2 itself (how remote play is implemented for Destiny 2). Can you test an L1 long press with Destiny 2 with the official remote play app from Sony on a supported device?

Also, here is a build where you can see if L1 is pressed or not: https://github.com/streetpea/chiaki-ng/actions/runs/11621171786/artifacts/2131058952. One long press would be L1 showing in a pressed state continually without an unpressed state in between.  Using this build, I can see that L1 never sends an unpressed signal if I hold L1 on my Steam Deck. Thus, it should be seen as one press that never ends, not multiple presses. You can see if the same is true on your Steam Deck.

To use this build you can first unzip it to your downloads folder and then make it executable with:
```
chmod +x ~/Downloads/chiaki-ng.Appimage
```
and then open it with:
```
~/Downloads/chiaki-ng.Appimage
```
Then, close it and you can copy settings from the flatpak with
```
cp ~/.var/app/io.github.streetpea.Chiaki4deck/config/Chiaki/Chiaki.conf ~/.config/Chiaki/Chiaki.conf
```
Then you can launch it again and use it.

**Comment by krozgrov** [comment]
Even using my Backbone and the official remote play app that same issue exist were holding L1 does not behave correctly through remote play as it does playing directly on the console.  You must be spied on and it’s an issue with the game itself and how it’s handling that particular request..

**Comment by streetpea** [comment]
@krozgrov that’s unfortunate. There is probably nothing I can do to fix it then. Bungie probably needs to fix it in their remote play implementation for the game.

**Comment by krozgrov** [comment]
I am an idiot, this whole issue was because my son updated my build....  I bought you some coffee for your help @streetpea!
