### ISSUE TITLE
Is there command line to get into a certain console on Windows?

### ISSUE THREAD

**Issue by Jayinem** [streetpea/chiaki-ng#441]
I read through all the releases and got excited when it said there was command line for profile, but that seems to be not console specific and in regards to someone's profile who may have multiple consoles connected? Or am I misunderstanding?

**Describe the solution you'd like**
I want to use command line to launch into specific console of my choosing, so that I can turn it into autohotkey scripts to where I can launch into each console by hitting a certain keyboard key of my choosing. 

If this is not current an option, I would like to make this a feature request.

**Comment by streetpea** [comment]
You can setup autoconnect with different profiles and launch it that way. Just select autoconnect for the given console in each given profile.

you can also manually select the console in the CLI but that’s not available on Windows

**Comment by Jayinem** [comment]
Oh I get it now, thank you.

**Comment by Jayinem** [comment]
Oh ok I get it now, but what are the command lines besides --profile=profile_name? Would I just put the command prompt window in the path and .\chiaki.exe --profile=profile_name? Could I get a list of command prompts? I'm decent at autohotkey but not great with command line.

**Comment by streetpea** [comment]
You need to register the consoles under each profile. You can always export the existing profile to .ini format using settings->config->export settings to file … then edit the file and change the profile name in the ini file and then import the “new” profile that copied the old profile with a new name

**Comment by Jayinem** [comment]
By exporting the default .ini and importing them to the other profiles, I was able to select autoconnect for each console for each profile. I think all I need are the command lines. 

thanks for your help

**Comment by Jayinem** [comment]
Yeah exporting/importing inis worked, the only thing I need are the command lines please? I  tried cd to where my chiaki ng is installed, and then .\chiaki.exe --profile=profile_name but it just opens the gui? What exactly do I need to type in?

**Comment by streetpea** [comment]
In the windows shortcut you should be able to add launch options and just add --profile=profile_name

**Comment by streetpea** [comment]
You need to go into each profile to consoles and check autoconnect for the console you want to launch into

**Comment by Jayinem** [comment]
I tried adding --profile=profile_name such as --profile=PS5 which is actually one of my profile names, but it says the path is invalided.

**Comment by Jayinem** [comment]
Nevermind I left a " that i needed to just delete it worked! tyvm, I didn't even know chiaki was still being worked on until you told me today. It's way better than the old one. Closing now.
