### ISSUE TITLE
[BUG] If a use RustDesk (which is like TeamViewer, let's me have access to another computer) Chiaki controller doesn't work

### ISSUE THREAD

**Issue by Jayinem** [streetpea/chiaki-ng#446]
I am not really sure if this is a bug or not, maybe it should do this, but I use RustDesk which is like a free TeamViewer. I access my other computer with it all the time.  But if I click on the RustDesk window my Chiaki controller no longer works. I have to click back on the Chiaki stream to make it work again. I would not even make a post about this but if I play a PC game for example while clicking on RustDesk window the controller continues to work. It only happens in Chiaki.

**Comment by streetpea** [comment]
@Jayinem that is the default behavior of SDL. There is a hint to change this behavior for controller events but I didn’t set it. I could give an option for this to be set if it’s really important to you.

**Comment by Jayinem** [comment]
I would appreciate it but if you don't it's okay. It's just that I even use an app called client-rs on my Nintendo Switch and it's not effected by it, PC games aren't effected by it, literally the only app effected is Chiaki. However I did try the original Chiaki and it did the same thing.

**Comment by streetpea** [comment]
@Jayinem like I said it’s the sdl default so any app using that and not changing the default will have that behavior. I’ll make a setting you can toggle for this today and post an updated build for you.

**Comment by streetpea** [comment]
@Jayinem actually when I was testing this, it already lets you use it in the background, even though it says the sdl default is for events to be only if the program is selected. At first I tried firefox, but then I even installed rustdesk and clicked on it and was still able to use a controller with chiaki-ng in the background (using an xbox controller). Not sure what is going on in your system. Are you using windows 11?

https://github.com/user-attachments/assets/c3145402-dc30-46f5-a22b-ac243d39e1b2

**Comment by Jayinem** [comment]
Still on Windows 10, if I click on Rustdesk the controller no longer works at all, I have to click back on Chiaki to get it to work again.  

I just tried your new build I did check the box about controller focus and it still does not work if I click on RustDesk, but even an alternative called AnyViewer focus remains, Firefox or any other app is fine. Not sure why I only have this issue with RustDesk and you said it worked for you. Oh well.

**Comment by streetpea** [comment]
@Jayinem does it work when rust desk is open in the settings of rust desk? It works for me in the settings of rust desk as I showed in the video I attached to my comment. I haven’t actually tried launching into a session on rust desk as I didn't set it up to actually use just to test with Chiaki-ng so maybe that’s the difference but if it doesn’t work in the settings of rust desk for you then something weird is going on as it works for me on 2 different computers (1 windows 10 and 1 windows 11)
