### ISSUE TITLE
How to turn off the profrmance mangohud on chiaki-ng 

### ISSUE THREAD

**Issue by abinmansour** [streetpea/chiaki-ng#451]
Hi 
I have troubled with the mangohud it is not responding to my setup on mangohud when I trun it off with shift and F12 
on my pc 
found in yellowish marker in this photo
![Screenshot from 2024-11-01 03-03-44](https://github.com/user-attachments/assets/7d3cf0ff-3a37-4326-b745-b3c9815627fe)

so is there a way to turn it off 
Btw using Nobara 40 on flatpak

**Comment by streetpea** [comment]
The mangohud isn’t controlled by chiaki-ng or interacted with chiaki-ng so I’m closing this as it’s not related to chiaki-ng

**Comment by abinmansour** [comment]
does anyone know how to turn it off ?

**Comment by streetpea** [comment]
You can turn it off from the Steam performance overlay settings in big picture mode
