### ISSUE TITLE
chiaki.exe no longer will run on my computer, Windows 10

### ISSUE THREAD

**Issue by Jayinem** [streetpea/chiaki-ng#456]
I was just using it maybe 4-5 days ago, but now when I go to run chiaki.exe it does nothing. I have 3 different folders set up for each of my two PS4s and a PS5, all 3 do nothing. So I thought I'll download the latest version of chiaki, but even it doesn't run. I have no idea what's going on I disabled my AVG but that didn't solve it. Tried rebooting no help. My computer is running fine otherwise, I have hundreds of PC games and I tested a bunch of them just in the last 2 days and they all run, I don't understand this. 

I just tried the original chiaki the non-ng version, and it runs. It's just your ng chiaki's that won't start.

**Comment by Jayinem** [comment]
I just deleted chiaki folder in registry HKEY_CURRENT_USER > Software, but even that didn't help.

**Comment by streetpea** [comment]
The original Chiaki doesn’t use Vulkan, chiaki-ng does. Your Vulkan is probably messed up. D3d games wouldn’t be affected (which is most windows games), Vulkan games would be affected. You can launch debug view on your computer to see why it won’t start

**Comment by Jayinem** [comment]
You're right it says vulkan is the cause, how do I fix that?

[20200] chiaki.gui: [libplacebo] Failed initializing vulkan instance

**Comment by Jayinem** [comment]
I deleted some display settings in registry a few days ago I just remembered that may have caused it. But reinstalling newest nvidia drivers settled it. Thanks for the help, as usual.
