### ISSUE TITLE
[BUG] AppImage Missing `libva-drm.so.2` Dependency

### ISSUE THREAD

**Issue by balajsra** [streetpea/chiaki-ng#459]
**Describe the bug**
AppImage is missing the `libva-drm.so.2` dependency.

**Debug Log**
```bash
$ chmod +x chiaki-ng.AppImage
$ ./chiaki-ng.AppImage
/tmp/.mount_chiakiy3r9sH/AppRun.wrapped: error while loading shared libraries: libva-drm.so.2: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. Download latest release (1.9.1) AppImage: `wget https://github.com/streetpea/chiaki-ng/releases/download/v1.9.1/chiaki-ng.AppImage.zip`
2. Unzip release file: `unzip chiaki-ng.AppImage.zip`
3. Make AppImage executable: `chmod +x chiaki-ng.AppImage`
4. Run AppImage: `./chiaki-ng.AppImage`

**Expected behavior**
Application should run

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Gentoo
 - Version: 2.17
 - Device: System76 Oryx Pro 7
 - chiaki-ng Version: 1.9.1

**Additional context**
Per the [AppImage page on the Gentoo Wiki](https://wiki.gentoo.org/wiki/AppImage), I have [sys-fs/fuse](https://packages.gentoo.org/packages/sys-fs/fuse) installed in slot 0. So all other dependencies should be packaged with the AppImage itself.

**Comment by streetpea** [comment]
There are a couple of dependencies which need to be installed on the host system since the appimage itself could package those but it would likely be incompatible with your hw drivers due to the differences in kernel version. For that reason libva, libvulkan, and libhidapi are purposefully excluded from the appimage and need to be installed locally on your system.

**Comment by balajsra** [comment]
Fair enough, thanks. Installing `media-libs/libva` fixed the issue. For others on Gentoo who may run into the same issue, I have made a package called [games-util/chiaki-ng-bin](https://github.com/balajsra/sravan-overlay/tree/main/games-util/chiaki-ng-bin) on my personal overlay which now includes the aforementioned dependencies.
