### ISSUE TITLE
[BUG] Remote connection not working Win 11 Rog Allyx

### ISSUE THREAD

**Issue by tdj88** [streetpea/chiaki-ng#460]
**Describe the bug**

When trying to connect remotely  all I get is "PSN couldn't establish connection with Playstation.Please try again.."

**Debug Log**
Please attach a log with verbose logging enabled.
[chiaki_session_2024-11-07_09-28-05-148148.log](https://github.com/user-attachments/files/17663014/chiaki_session_2024-11-07_09-28-05-148148.log)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version [
 - 24H2
 - Device ALLY X
 - chiaki-ng Version: Latest 

**Additional context**
I'm able to connect remotely with PS remote Play.

**Comment by streetpea** [comment]
@tdj88 if you are getting this consistently it likely means your PlayStation is not connected to PSN or not up to date firmware wise as it means PSN can’t contact your PlayStation. Can you connect with the official remote play app?

**Comment by tdj88** [comment]
yes I'm able to use remote play off local wifi.  via Hotspot

**Comment by tdj88** [comment]
[chiaki_session_2024-11-07_12-26-02-514514.log](https://github.com/user-attachments/files/17667270/chiaki_session_2024-11-07_12-26-02-514514.log)
@streetpea

**Comment by streetpea** [comment]
@tdj88 thanks, sorry about that. Can you try this build: https://github.com/streetpea/chiaki-ng/actions/runs/11730613467/artifacts/2159913711?

**Comment by tdj88** [comment]
@streetpea we got further then before. but drops at video connection
[chiaki_session_2024-11-07_16-04-22-932932.log](https://github.com/user-attachments/files/17669457/chiaki_session_2024-11-07_16-04-22-932932.log)

**Comment by streetpea** [comment]
@tdj88 it looks like you're losing connection to PSN after 10 seconds. The timeout is 10 seconds but it should only hit if no messages are received and you are getting PONGs so it definitely is receiving them so not sure why the connection is being terminated. You can try https://github.com/streetpea/chiaki-ng/actions/runs/11732706685/artifacts/2160552845 to see if it fares any better.

**Comment by tdj88** [comment]
@streetpea yeah not working at all 
[chiaki_session_2024-11-07_18-32-32-430430.log](https://github.com/user-attachments/files/17670908/chiaki_session_2024-11-07_18-32-32-430430.log)

**Comment by streetpea** [comment]
here is another build to try @tdj88 https://github.com/streetpea/chiaki-ng/actions/runs/11740517681/artifacts/2162516502

**Comment by tdj88** [comment]
@streetpea that build not working. I am able to connect to ps remote play via  Hotspot.
<img width="734" alt="image" src="https://github.com/user-attachments/assets/b02570dc-e308-42af-a5c7-2ef7fead524d">

**Comment by streetpea** [comment]
@tdj88 can you post an updated log. It should be able to connect bc you are actually able to establish the connection to the PlayStation fine but the websocket connection to the psn server is getting disrupted during setup. I have never actually seen this before and not sure what’s causing it.

**Comment by tdj88** [comment]
@streetpea  here are the last  3 ( sidenote: I just tried PXplay I was able to connect remotely on it, now it did take a while to connect but eventually it connected. I'm doing some verification. I will let you know what my results are.
[chiaki_session_2024-11-08_09-37-04-961961.log](https://github.com/user-attachments/files/17680202/chiaki_session_2024-11-08_09-37-04-961961.log)
[chiaki_session_2024-11-08_09-37-04-969969.log](https://github.com/user-attachments/files/17680203/chiaki_session_2024-11-08_09-37-04-969969.log)
[chiaki_session_2024-11-08_09-38-05-518518.log](https://github.com/user-attachments/files/17680204/chiaki_session_2024-11-08_09-38-05-518518.log)

**Comment by tdj88** [comment]
@streetpea here is a Wireshark 
[psn network.zip](https://github.com/user-attachments/files/17680834/psn.network.zip)

**Comment by streetpea** [comment]
@tdj88 this build should fix the issue: https://github.com/streetpea/chiaki-ng/actions/runs/11745457550/artifacts/2163979586

**Comment by tdj88** [comment]
@streetpea HOLY COW!!! it finally worked good stuff. Do you know the cause of it acting the way it did?

**Comment by streetpea** [comment]
@tdj88 the timeout for the ws initiating was getting applied to the websocket itself. This is a libcurl websocket bug that only happens on specific configurations. For whatever reason, your system configuration was triggering it. I worked around the bug by setting the initial connection to never time out.

**Comment by streetpea** [comment]
Fixed by 69545894d8eaa85f201224bfb507ecfc773ff6cb
