### ISSUE TITLE
[BUG] Chiaki4Deck-Win not launching

### ISSUE THREAD

**Issue by Lastlink15** [streetpea/chiaki-ng#461]
**Describe the bug**
I have already tried this solution (https://www.reddit.com/r/ROGAlly/s/ZmTuVwQtY9), but apparently I do not have any OpenCL, GL, vulkan package installed...

**Debug Log**
N/A

**To Reproduce**
Download
Extract
Try to run

**Expected behavior**
Chiaki UI
**Screenshots**

![image](https://github.com/user-attachments/assets/b9d7e4af-197a-401b-a5bf-d3f22a49e0c2)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Home Single Lenguage
 - Device Aspire 3 A315-53
 - chiaki-ng Version: Win_x64-VC, Win_x64-MSYS2

**Additional context**
I've tried with Chiaki4deck too, same problem. (PS Remote-Play runs fine)

**Comment by streetpea** [comment]
@Lastlink15 it’s most likely a Vulkan problem with your pc can you paste the output of debug view https://learn.microsoft.com/en-us/sysinternals/downloads/debugview

**Comment by Lastlink15** [comment]
> @Lastlink15 it’s most likely a Vulkan problem with your pc can you paste the output of debug view https://learn.microsoft.com/en-us/sysinternals/downloads/debugview? Open debug view first and then launch chiaki-ng

[12144] chiaki.gui: [libplacebo] Initialized libplacebo v7.349.0 (v7.349.0) (API v349)
[12144] chiaki.gui: [libplacebo] Instance API version 1.1.0 is lower than the minimum required version of 1.2.0, cannot proceed!
[12144] chiaki.gui: [libplacebo] Failed initializing vulkan instance

**Comment by streetpea** [comment]
It seems your Vulkan version isn’t high enough to run chiaki-ng. If possible, update your gpu/cpu driver to a newer one

**Comment by Lastlink15** [comment]
> It seems your Vulkan version isn’t high enough to run chiaki-ng. If possible, update your gpu/cpu driver to a newer one. It needs to support at least Vulkan 1.2.0

You were right. I updated my driver (two versions older than the most recent one that could be installed) and it works now, Thanks

![image](https://github.com/user-attachments/assets/00033339-5fba-4830-90b9-f3004a61a5e9)

**Comment by Lastlink15** [comment]
Solved, thanks streetpea
