### ISSUE TITLE
Add a fixed size Window Type

### ISSUE THREAD

**Issue by andshrew** [streetpea/chiaki-ng#462]
**Is your feature request related to a problem? Please describe.**
I use chiaki in window mode, so I have **Video -> Window Type** set to **Select Resolution**.  

When I connect, my window is automatically sized to match the streams resolution. I can then manually resize the window back to the size I want it to be, and chiaki automatically scales the stream to fit. 

**Describe the solution you'd like**
It would be nice if there was an additional **Window Type** option where it would either keep the current application window size, or allow you to set a fixed size. This would save having to re-size the stream window back to the size I want it to be whenever I connect.

**Additional context**
Example of current behaviour:
![Example of current behaviour](https://imgur.com/U5ORQ2i.gif)

**Comment by streetpea** [comment]
@andshrew what platform are you on for a test build?

**Comment by andshrew** [comment]
Windows would be preferred, but I could do Mac.

Thanks

**Comment by streetpea** [comment]
@andshrew here is a windows build: https://github.com/streetpea/chiaki-ng/actions/runs/11749648283/artifacts/2165222739

**Comment by andshrew** [comment]
That is exactly what I was looking for, thank you!

I have my stream set to 1080p and the window set to 720p and it seems to be working exactly as expected.
