### ISSUE TITLE
WinGet / Chocolately  Support

### ISSUE THREAD

**Issue by dkflint723** [streetpea/chiaki-ng#466]
**Is your feature request related to a problem? Please describe.**

Instead of downloading via github I'd love to see the windows version available via other download options.

**Describe the solution you'd like**

I'd love to see chiaki-ng being installable via winget and/or chocolately on windows.

**Comment by streetpea** [comment]
@dkflint723 great idea. I think the first step would be to make an installer. Innosetup (https://jrsoftware.org/isinfo.php) seems like a good option.

**Comment by streetpea** [comment]
I opened a pull request to add a winget package here https://github.com/microsoft/winget-pkgs/pull/190343

**Comment by dkflint723** [comment]
Thanks, @streetpea; I appreciate that you decided this was a good idea. I usually try use UniGetUI (https://github.com/marticliment/UnigetUI) to manage the majority of my software if I can. So, this was a pretty selfish request, but I'm glad you went with it.

**Comment by streetpea** [comment]
Update: winget package added (currently 1.9.1 with update to 1.9.3 in progress), chocolatey package still in moderation phase

**Comment by streetpea** [comment]
Winget and chocolatey packages are now available (winget is at 1.9.3 + upgrade from 1.9.1 to 1.9.3 for chocolatey package is in progress now that 1.9.1 is approved)
