### ISSUE TITLE
[BUG] not creating ddl files

### ISSUE THREAD

**Issue by ttoille123** [streetpea/chiaki-ng#468]
**Describe the bug**
A bunch of .dll files are not installing for either user only and system wide for windows even when reinstalling

**To Reproduce**
Install program
Try to run
A bunch of errors stating "The cod excution cannot procesd because" [Insert .dll file here](avcode-61.dll, etc.) "was not found. Reinstalling the program may fix this problem"
 - OS: Windows
 - Version 23H2
 - Device Windows PC
 - chiaki-ng Version 1.9.1

**Comment by streetpea** [comment]
@ttoille123 the installer script that got added today was given the wrong directory at the last minute when I was editing it. I changed it to the correct directory. If you reinstall the installer, it should work now.
