### ISSUE TITLE
[BUG] ROG Ally missing DLLs

### ISSUE THREAD

**Issue by NeilGraham** [streetpea/chiaki-ng#471]
**Describe the bug**

Getting the following error 4x times after installing on the original ROG Ally with the latest updates & BIOS.

```
The code execution cannot proceed because {DLL} was not found. Reinstalling the program may fix this problem.
```
- DLLs not found:  `libplacebo-349.dll` `avcodec-61.dll` `avutil-59.dll` `Qt6Svg.dll`

chiaki-ng completes installation but does not start as a result of the errors. Reinstalling multiple times results in the same errors and issues.

**Desktop:**
 - OS: Windows 11
 - Device: ROG Ally
 - chiaki-ng Version: v1.9.1

**Comment by streetpea** [comment]
@NeilGraham can you try redownloading it?

**Comment by NeilGraham** [comment]
> @NeilGraham can you try redownloading it? There was an issue with the new installer posted yesterday that was fixed later that day. Possibly, you grabbed it in between that time.

Yes that was the issue, able to install and run the app now. Thank you!
