### ISSUE TITLE
[BUG] Remote PSN uPnP mapping method not working in 1.9.1

### ISSUE THREAD

**Issue by Rahzadan** [streetpea/chiaki-ng#474]
**Describe the bug**
uPnP mapping does not work in version 1.9.1, and always falls back to STUN for Remote PSN. STUN works, but is less ideal.

**Debug Log**

See lines **243, 866, 3482 and 3483** in the 1.9.0 log showing uPnP functioning correctly:

[1.9.0 - chiaki_session_2024-11-13_11-06-45-634634.log](https://github.com/user-attachments/files/17734713/1.9.0.-.chiaki_session_2024-11-13_11-06-45-634634.log)

See line **19** showing Chiaki failing to find any uPnP devices on the network:

[1.9.1 - chiaki_session_2024-11-13_10-56-36-998998.log](https://github.com/user-attachments/files/17734714/1.9.1.-.chiaki_session_2024-11-13_10-56-36-998998.log)

**To Reproduce**
1. Run Chiaki-ng 1.9.0
2. Connect to PS5 with discovery disabled, to force it to connect via PSN.
3. uPnP connection succeeds and Chiaki maps ports via uPnP successfully
4. Run Chiaki-ng 1.9.1
5. Connect to PS5 with discovery disabled, to force it to connect via PSN.
6. uPnP connection fails and **always** connects to PS5 via STUN instead, regardless if uPnP is enabled on the network or not.

**Expected behavior**
That Chiaki-ng connects via uPnP when it is available and enabled on the network. 1.9.0 does this - 1.9.1 does not.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11
 - Device Desktop and Laptop PC
 - chiaki-ng Version 1.9.0 and 1.9.1

**Additional context**
I tested this on 2 different Windows 11 PCs. My laptop and my desktop PC, and this behaviour was identical on both. Also note that I made no modifications to the Chiaki-ng configuration when swapping between 1.9.0 and 1.9.1. The PS5 also correctly maps its own ports via uPnP in every instance.

**Comment by streetpea** [comment]
@Rahzadan please try this build to make sure it fixed the issue https://github.com/streetpea/chiaki-ng/actions/runs/11826182325/artifacts/2184547718

**Comment by Rahzadan** [comment]
@streetpea The above build properly initiates a uPnP connection :) Awesome!

> [2024-11-13 23:33:06:034034] [I] holepunch_session_create_offer: Added local UPNP port mapping to port 56892
