### ISSUE TITLE
[BUG] Black screen Chiaki ng Windows 11

### ISSUE THREAD

**Issue by Karmagus78** [streetpea/chiaki-ng#478]
<img width="1565" alt="Capture d’écran 2024-11-17 232546" src="https://github.com/user-attachments/assets/f8b61d67-3d79-467e-9975-4c947b489291">

I have a black screen when I open the application

I have installed the application several times but still does not work

**Comment by streetpea** [comment]
@Karmagus78 is this when streaming or just opening the application? Also, do you have the latest drivers installed for your graphics card?

**Comment by Karmagus78** [comment]
When launching the application

but indeed I updated my graphics driver and it works, thank you
