### ISSUE TITLE
Mouse support for supported games

### ISSUE THREAD

**Issue by WajahatAliShah1** [streetpea/chiaki-ng#486]
**Is your feature request related to a problem? Please describe.**
Chiaki currently relies on remapping mouse and keyboard inputs to emulate a controller, which limits precision and responsiveness in supported games. It also is limited in terms of functionality, as there is no cursor/navigation support in game. Native support for these peripherals would replicate the experience of directly connecting them to a PS5.

**Describe the solution you'd like**
Add native mouse and keyboard support to Chiaki, enabling direct input recognition by the PS5. 
This would include:
- Getting native inputs working properly for games that support mouse and keyboard.
- Sensitivity adjustments and key mapping options.
- Seamless integration with the existing Chiaki UI.

**Describe alternatives you've considered**
Controller remapping: Functional, but comes with limitations + no real cursor support.
External adapters: Same issues but expensive and inconvenient.

**Comment by streetpea** [comment]
closing as direct mouse control isn't currently exposed by PlayStation remote play so implementing this as it stands now is impossible.
