### ISSUE TITLE
[BUG] 1.9.1 DECK Import / export settings gui broken

### ISSUE THREAD

**Issue by chanksworld** [streetpea/chiaki-ng#489]
Menu is broken to import or export settings on OLED deck. Too small to select anything. Results are same in desktop or game mode 

![image](https://github.com/user-attachments/assets/43a4cc4d-adef-4d55-a342-0e53912138fa)

**Comment by streetpea** [comment]
@chanksworld are you trying to run it via Steam? Steam blocks the file browser functionality. You need to use the KDE file browser via the application in desktop mode outside of Steam. Doing that I get a menu like the following with 1.9.1
![ExportProfileMenuSteamDeck](https://github.com/user-attachments/assets/b9b74011-8b3a-4eaf-bba0-736fec6c479f)

**Comment by chanksworld** [comment]
@streetpea  I get the same result in game mode. could it be because i'm using the appimage?

**Comment by streetpea** [comment]
It doesn’t work in game mode. Only desktop mode. I was using the flatpak. I’ll try the appimage.

**Comment by streetpea** [comment]
@chanksworld that was indeed it. It works in the flatpak but not in the appimage.

**Comment by streetpea** [comment]
So there was a bug with the qml native File Dialog in Qt. I switched to using the QFileDialog from c++ and it works now. Here is an updated appimage that should work @chanksworld https://github.com/streetpea/chiaki-ng/actions/runs/12110850697/artifacts/2259164621

**Comment by streetpea** [comment]
https://github.com/streetpea/chiaki-ng/actions/runs/12118386272/artifacts/2261049344
