### ISSUE TITLE
Linux aarch64/arm64 build without flatpak

### ISSUE THREAD

**Issue by x13-me** [streetpea/chiaki-ng#496]
**Is your feature request related to a problem? Please describe.**
I cannot run chiaki-ng on linux-aarch64 without flatpak; the AppImage is x86_64 only

**Describe the solution you'd like**
A linux aarch64 build to be created

**Describe alternatives you've considered**
No alternatives

**Additional context**
None

**Comment by streetpea** [comment]
@x13-me qt supports linux arm releases as of 6.7 and we can use docker's multi-arch capabilities to build an arm Linux appimage on x86 builders. I'll look into building an appimage for arm64/aarch64 on Linux

**Comment by streetpea** [comment]
@x13-me can you test this arm64 appimage and make sure it’s working: https://github.com/streetpea/chiaki-ng/actions/runs/12285643986/artifacts/2308807267?

**Comment by x13-me** [comment]
> @x13-me can you test this arm64 appimage and make sure it’s working: https://github.com/streetpea/chiaki-ng/actions/runs/12285643986/artifacts/2308807267?

Works as far as I can test, running into graphics drivers issue now.

Thanks for this!
