### ISSUE TITLE
[BUG] Remote Play does not start if console has a login passcode

### ISSUE THREAD

**Issue by Yemi-1020** [streetpea/chiaki-ng#497]
**Describe the bug**
When trying to connect to my PS5 console via a local connection, it is able to wake up the console from rest mode but the chiaki-ng is continuously waiting for a stream while nothing comes through.

Previously chiaki-ng would prompt for a console pin allow me to enter it and then the remote play would be established and it worked fine. The last time I was able to get successful remote connection was around 21/11/2024, I had since not used it until now.

Additionally if a pin is removed from the console, upon trying to start remote play, the remote play does not seem to automatically start. I still have to press the Playstation button on my Dualsense controller before remote play starts and I'm not entirely sure if this is intended but what I have troubleshooted, remote play does seem to start in this case. Not entirely sure if it starts reliably here.

**To Reproduce**
1. Enable login passcode for PS5
2. On Chiaki-ng, click on console to start remote play (do not provide console pin for registered console)

**Expected behavior**
Chiaki-ng should prompt for console login passcode, one entered remote play should start working.

**Screenshots**
![Screenshot_20241209_112421](https://github.com/user-attachments/assets/e92a9540-a3f9-4b7b-a8f3-b462de636acf)

**Desktop:**
 - OS: Fedora 41
 - Device: Desktop PC 
 - chiaki-ng version: 1.9.2 (Flatpak)

**Comment by streetpea** [comment]
Can you attach a log file? Using a pin prompts me for a pin or allows me to enter it on my console. Can you try with the official remote play app?

**Comment by Yemi-1020** [comment]
[chiaki_session_2024-12-09_11-23-50-783783.log](https://github.com/user-attachments/files/18069156/chiaki_session_2024-12-09_11-23-50-783783.log)
[chiaki_session_2024-12-09_11-12-54-985985.log](https://github.com/user-attachments/files/18069157/chiaki_session_2024-12-09_11-12-54-985985.log)

I've attached two log files if that helps. I've tried:

- Restarting the PS5
- Turning it off completely and back on
- Deleting the console of Chiaki and registering it again
- Removing the login passcode

Only the last action did anything and even then, it still required to press the PlayStation button on my controller to actually get remote play working which seems a little odd.

**Comment by streetpea** [comment]
@Yemi-1020 can you please try this appimage build: https://github.com/streetpea/chiaki-ng/actions/runs/12246329988/artifacts/2296956554?

You can first unzip it to your downloads folder and then make it executable with:
```
chmod +x ~/Downloads/chiaki-ng.Appimage
```
and then open it with:
```
~/Downloads/chiaki-ng.Appimage
```
Then, close it and you can copy settings from the flatpak with
```
cp ~/.var/app/io.github.streetpea.Chiaki4deck/config/Chiaki/Chiaki.conf ~/.config/Chiaki/Chiaki.conf
```
Then you can launch it again and use it.

**Comment by Yemi-1020** [comment]
Looks like the appimage is refusing to launch, it throws the following error

`/tmp/.mount_chiakiyCwSJU/AppRun.wrapped: error while loading shared libraries: libhidapi-hidraw.so.0: cannot open shared object file: No such file or directory
`

**Comment by streetpea** [comment]
@Yemi-1020 it requires you manually installing hidapi because bundling it with the appimage doesn’t work.

**Comment by streetpea** [comment]
So 
```sudo yum install hidapi```

**Comment by Yemi-1020** [comment]
So it looks like the same issue is still occurring. Additionally attempting to close Chiaki causes it to freeze and I'm unable to fully close until I reset my PC. This also happens with the flatpak version.

**Comment by Yemi-1020** [comment]
Actually nvm, the AppImage can actually actually be terminated by force unlike the flatpak. So that's at least one better outcome.

**Comment by streetpea** [comment]
@Yemi-1020 can you post a new log?

**Comment by Yemi-1020** [comment]
[chiaki_session_2024-12-10_00-44-14-931931.log](https://github.com/user-attachments/files/18069872/chiaki_session_2024-12-10_00-44-14-931931.log)
[chiaki_session_2024-12-10_00-49-19-619619.log](https://github.com/user-attachments/files/18069873/chiaki_session_2024-12-10_00-49-19-619619.log)

**Comment by Yemi-1020** [comment]
Just to add, I tried the remote play app on my phone and that seems to work correctly.

**Comment by streetpea** [comment]
It seems the change I made wasn’t applied from your logs. Looking into it.

**Comment by streetpea** [comment]
@Yemi-1020 are you sure you downloaded and extracted the right appimage file to your desktop (the one linked above)? The log files you posted indicate the change didn’t take affect but testing it on my desktop it does show the appropriate logs.

**Comment by Yemi-1020** [comment]
Apologies, I did download the wrong on. Let me try that again.

**Comment by streetpea** [comment]
Basically the wait for the login pin request just wasn’t long enough in rare instances. In most cases it is which is why others aren’t necessarily running into it but yours was taking some milliseconds over 5 seconds. I changed the wait time to 10 seconds which should eliminate this problem.

**Comment by Yemi-1020** [comment]
That makes sense, thanks a bunch for your hard work on this project.

**Comment by streetpea** [comment]
It's fixed in the main code now and will be released with the next release. You can use that appimage until then.

**Comment by streetpea** [comment]
@Yemi-1020 after I updated my PS5 I immediately hit this so it's likely the new update made the init longer causing the issue now whereas it wasn't happening before.

**Comment by Yemi-1020** [comment]
That sounds about right, I think my ps5 had at least one update during the period I haven't used remote play and then I did an additional update when troubleshooting.
