### ISSUE TITLE
[BUG] Steam Deck - touch pad "T" key does not work with PS1, PS2, and PSP games.

### ISSUE THREAD

**Issue by Toki-Rumpii** [streetpea/chiaki-ng#502]
While playing on PS4 and streaming to Steam Deck, PS1, PS2, and PSP games does not recognize the touchpad "T" command. 

The "T" key does not input when registered to any button. 

I did test the PS4 Ratchet and Clank game and the touchpad "T" command did function properly. 

Games I specifically tried were:

Toy Story 2 (PS1)
Jak & Daxter (PS2)
Daxter (PSP)

The first time you start any old game there is a blue screen explaining that you use the touchpad for "Start" and "Select" and you must hit "Start" on the touch pad to proceed. The issue is present from here forward. The blue screen should only appear once. But regardless the touchpad "T" command does not function on this blue screen or after. 

Now that I think about I don't think Chiaki currently has anyway to input anything for "Select"

12-11-24 PS4, Steam OS, and Chiaki are all updated to the latest version.

**Comment by streetpea** [comment]
@Toki-Rumpii did you add chiaki-ng to steam using the button in-app?

**Comment by streetpea** [comment]
I would assume what’s happening is that you need touch input in addition to the button itself for this to work and this is setup by default if you add the game through the shortcut in the app as the default steam deck controller profile is applied.

**Comment by Toki-Rumpii** [comment]
I was using an old version of Chiaki from Florian Märki. I switched to your -ng version and everything is working great. Thank you for taking time to respond and for your efforts on Chiaki :)
