### ISSUE TITLE
[BUG] Doesn't connect after update

### ISSUE THREAD

**Issue by PFernandes5846** [streetpea/chiaki-ng#506]
**Describe the bug**
After updating to version 1.9.3 I cannot connect to the PS5. I can log into the chiaki4deck app, but when I try to connect to the PS5, the app closes and I'm returned to the SteamOS main menu.

**Debug Log**
Please attach a log with verbose logging enabled.

**To Reproduce**

**Expected behavior**
Connect to PS5

**Screenshots**

**Desktop (please complete the following information):**
 - OS: SteamOS
 - Version Beta 3.6.21
 - Device Steam Deck
 - chiaki-ng Version 1.9.3

**Additional context**

**Comment by streetpea** [comment]
@PFernandes5846 please attach a log with debug login enabled.

**Comment by PFernandes5846** [comment]
[chiaki_session_2024-12-15_01-11-35-157157.log](https://github.com/user-attachments/files/18138492/chiaki_session_2024-12-15_01-11-35-157157.log)

**Comment by streetpea** [comment]
@PFernandes5846 did you install any new graphics drivers?

**Comment by streetpea** [comment]
It looks like your graphics driver doesn’t support outputting zero copy to a hdr output format but the Steam deck’s default one does and works fine for me so that’s why I think perhaps your driver is messed up.

**Comment by PFernandes5846** [comment]
I don't have an external GPU. I only updated the Decky Loader and the updates available on Discovery, nothing else.

**Comment by streetpea** [comment]
The error you are currently running into is using code that was not changed in the update si something else changed on your system

**Comment by PFernandes5846** [comment]
I also updated SteamOS to this version:
https://www.steamdeck.com/en/news
Do you think it might have been due to this update?

I changed the codec to standard H265 and now it works. But I would like to have HDR working again. Thanks for the support.

**Comment by streetpea** [comment]
@PFernandes5846 after some testing it was Mesa's from 24.2.7 to 24.3.1 that broke it. 
Running the following command in the konsole (reverting your mesa version to 24.2.7 should fix it)
```
flatpak update --user --commit=10a5153b2b4aee357d43cecf7987ee972acd2d3d282b0f2e317c9caa4fd27c8c org.freedesktop.Platform.GL.default//24.08extra
```

**Comment by streetpea** [comment]
@PFernandes5846 alternatively you can switch hw decoder to vaapi in the video settings.

**Comment by streetpea** [comment]
fixed in 51fdfe6

**Comment by streetpea** [comment]
Thanks for reporting this @PFernandes5846 as a lot of users would have hit this if not worked around.

**Comment by PFernandes5846** [comment]
Man, you are the best! It's working with HDR. Thank you very much for the support. Top!
