### ISSUE TITLE
[BUG] PS5 Remote Play started once, now won't start

### ISSUE THREAD

**Issue by admapop** [streetpea/chiaki-ng#507]
**Describe the bug**
I am using chiaki4deck, I set up remote play, tested locally and remote via PSN and it worked.

I am now in a different location, across the country. I tried a remote session and it worked just fine! I put it back to rest mode and went to play again after a couple of hours. Now it won't start at all with the error message

`PSN couldn't establish connection with Playstation. Please try again...`

**Debug Log**
[Chiaki Session Dec 18 2024.log](https://github.com/user-attachments/files/18181243/Chiaki.Session.Dec.18.2024.log)

**To Reproduce**

**Expected behavior**
Expected behaviour is to connect via PSN

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Steam OS
 - Version Latest stable
 - Device Steam Deck
 - chiaki-ng Version 1.9.3

**Additional context**

**Comment by streetpea** [comment]
@admapop it seems you're console is not connected to PSN. Have you tried again to make sure it consistently does this? Maybe it got turned off somehow. Was there a power outage in your area? Can you try with the official remote play app and see if that works?

**Comment by streetpea** [comment]
@admapop have you done this:

Go to Settings -> System -> Power Saving -> Features Available in Rest Mode and turn on:

Stay Connected to the Internet
Enable Turning on PS5 from Network

**Comment by admapop** [comment]
> @admapop have you done this:
> 
> Go to Settings -> System -> Power Saving -> Features Available in Rest Mode and turn on:
> 
> Stay Connected to the Internet Enable Turning on PS5 from Network

Yes those were on. If it doesn't work again I think I might need to set a fixed IP for it and open the ports, although with UPnP I would have expected to not have to open ports

**Comment by streetpea** [comment]
@admapop this has nothing to do with opening ports. Specifically, it’s that the connection between your console and psn isn’t active. Of course, you could forward ports and connect directly instead of using psn to initially establish a direct connection between you and the console

**Comment by admapop** [comment]
It's working consistently now, it must have been some bug with PSN
