### ISSUE TITLE
[BUG] Broken Discord Link on README

### ISSUE THREAD

**Issue by ramirocantu** [streetpea/chiaki-ng#509]
**Describe the bug**
Under the Discord header in the readme, the hyperlink: [chiaki-ng community Discord](https://discord.gg/ZFPvd2vD) links to a dead invite.

**Debug Log**
n/a

**To Reproduce**
1. open README
2. Click on '[chiaki-ng community Discord](https://discord.gg/ZFPvd2vD)'

**Expected behavior**
be able to join a discord server to ask for support or share ideas.

**Screenshots**
<img width="995" alt="Screenshot 2024-12-20 at 10 42 15 PM" src="https://github.com/user-attachments/assets/40abd06a-55b8-4ca2-9c9e-6005c845efcc" />

**Desktop (please complete the following information):**
n/a
**Additional context**
n/a

**Comment by streetpea** [comment]
https://discord.gg/tAMbRuwXDH … I forgot to set the link to never expire. I created a new one that doesn’t expire. I updated the readme. I’ll update the docs when I get back to my computer tomorrow.

**Comment by streetpea** [comment]
It's updated in the docs as well now.

**Comment by ramirocantu** [comment]
thank you! @streetpea
