### ISSUE TITLE
[BUG]Missing library (libraries?) in AppImage on Fedora 41

### ISSUE THREAD

**Issue by delentef** [streetpea/chiaki-ng#511]
**Describe the bug**
Chiaki NG 1.9.3 doesn't start and gives this error:

`/tmp/.mount_chiaki9sYDyi/AppRun.wrapped: error while loading shared libraries: libhidapi-hidraw.so.0: cannot open shared object file: No such file or directory`

**Debug Log**
Not possible (app doesn't start)

**To Reproduce**
Type command ./chiagi-ng.AppImage in command line

**Expected behavior**
Program should start

**Desktop (please complete the following information):**
 - Fedora
 - 41
 - Asus ROG Strix ScarIII
 - chiaki-ng Version 1.9.3

**Additional context**
I guess the package was built without including all mandatory libraries

**Comment by streetpea** [comment]
@delentef see release notes: https://github.com/streetpea/chiaki-ng/releases/tag/v1.9.3 … hidapi needs to be installed as a library because packaging it with the app doesn’t give the required functionality.

**Comment by delentef** [comment]
Sorry for the noise, I didn't read the release notes!
