### ISSUE TITLE
Stream Needs to Stabilize for 5mins...

### ISSUE THREAD

**Issue by mufaaf** [streetpea/chiaki-ng#516]
Ok, so this is probably not a Chiaki issue (on the Steam Deck OLED) as it happens with PXPlay on a separate device, but I don't know where else to ask. Hopefully, someone has an idea.

So, from out of nowhere, my PS5 streams have started to stutter. A lot. Every single second. This probably kicked in after 30th anniversary update as I did not try streaming before the update.

Before the update (or a month or so ago), everything was peachy and smooth after I changed my router to a WiFi 6 one. It solved all my streaming issues on both my PC and PS5, and I was happy you can be about these things.

But now, the moment I start a stream, its a complete stuttery mess. I have tried going as low as 10K bitrate but the problem remains. I have also tried turning off HDR, using the Fast preset, changing decoder, Google DNS on the PS5, QoS on the router etc, but nothing works. However, if I load a game, and leave it alone for a few mins, the stream automatically stabilizes and everything is back to normal. I can play for hours without a single issue.

For example, I load up Marvel Rivals and it stutters every other second. But If I load into the tutorial mode, and leave it alone without touching the controller for 5mins, it stabilizes and works after that.

I don't have such problem with PC streaming via Moonlight + Sunshine.

My PS5 and SteamD are connected via WiFi 5Ghz channel. Yes, I know a wire would be better but I can't connect it to an ethernet in my setup. But that doesn't matter because it used to work before just fine. The problem have only recently started to develop, and why does it all work just fine after I leave it alone for a few mins? I have tested this "trick" multiple times now and works every time. I have not change a single setting on my router or the PS5 or anywhere else. I am absolutely confused why it shat the bed all of a sudden.

Any help or insight into this problem would be swell. Thanks for reading! :)

**Comment by streetpea** [comment]
@mufaaf the stream automatically continues to lower the bitrate upon package losses. It’s possible that is playing a part in what you’re experiencing. Can you try switching to 720p? It sounds like it may be a wifi issue with the ps5 and the connection stabilizes after a while. If it’s just constantly stuttering that means there are a ton of packet drops.

**Comment by mufaaf** [comment]
> @mufaaf the stream automatically continues to lower the bitrate upon package losses. It’s possible that is playing a part in what you’re experiencing. Can you try switching to 720p? It sounds like it may be a wifi issue with the ps5 and the connection stabilizes after a while. If it’s just constantly stuttering that means there are a ton of packet drops. It's possible you have some noisy neighbors interfering, Maybe someone set up more wifi or other networks and it's interfering. Have you tried 2.4 GHz and see if that's any better?

Just tried 720p and the result is the same. Plenty of dropped frames (22-40!), and tons of packet loss. And this time, it didn't even fully stabilize, but it did improve with only few packet loss and dropped frames.

On 2.4Ghz, Chiaki simply doesn't connect for me.

It could be wifi interference, but the internet as a whole works fine. I have tried different wifi channels, too, and that didn't help at all.

One more thing I should note: My mom was watching a live stream yesterday which was going smoothly without any stutter. But the moment I started Chiaki streaming, two mins in, the stream started to buffer and then entirely stop. I was like, huh? could it be?, so I turned off the PS5 and the live stream went back to normal. So I turned on the PS5 only, and the live stream was fine. I started Chiaki stream and the live stream went down again!

So...something is happening when PS5 starts streaming to Chiaki or PXPlay where it sort of brings the wifi connection to its knees. I have restarted the router but that didn't help either. I am utterly confused why this is happening all of a sudden. The router, and the internet connection, is pretty stable otherwise. I am getting max download speeds on the Steam Deck, which didn't happen with my old router.

**Comment by streetpea** [comment]
That honestly shouldn't be happening if the router isn't very old. What is the rating for the router for the 5GHz network for total throughput? For example, my new router that I just got for Christmas has 5400 Mbps total throughput possible with 2400 Mbps via 5GHz. The bitrate for chiaki-ng is in kpbs so a bitrate of 30,000 in chiaki-ng (30,000 Kbps) would take up 30 Mbps or about 1.25% of the total throughput of the router for 5GHz. If that number isn't close to at least 70% or something I wouldn't expect everything to come crashing down unless there is a serious problem with the router. Have you checked for router firmware updates? Dropped frames is one thing but completely losing internet connection is another, especially since chiaki-ng is probably just using a local connection so is only stressing the router and not the Wi-fi and same for pxplay.

**Comment by streetpea** [comment]
Are you using a mesh router? There's some settings on mesh routers that could cause your issue maybe.

**Comment by streetpea** [comment]
@mufaaf reading through your issue it sounds like maybe something is wrong with your ps5 wifi card since you say using the steam deck wifi is fine. Given streams buffer it is possible to have packet loss and still a relatively fast download stream but if your pc streams fine then the ps5 is likely your problem.  Even if you didn’t see artifacts you should see the same general packet loss with any game streaming software as the packets themselves are received using the same utilities baked in to the os.

**Comment by streetpea** [comment]
@mufaaf can you try downloading a game on your ps5 and see if that has any effect on your internet

**Comment by mufaaf** [comment]
> @mufaaf can you try downloading a game on your ps5 and see if that has any effect on your internet. Also since you mentioned being at home I’m assuming you’re using a local connection and not remote connection via psn.

Just tried downloading and then watching a Youtube stream and it was fine.

I have the TP Link Archer AX23, which supports 1201Mbps over 5Ghz, so that shouldn't be a problem me think? I can stream at 95mbps from my PC, but the PC is on ethernet mind you. Have not tried WiFi with PC because I don't have a mesh system and the WiFi is not strong in my living room and won't be a fair comparison.

There was a firmware upgrade for the router a little while ago....hmm, I wonder if thats what's caused the issue? Or it could be my PS5 wifi card. However, downloading games or playing online is just fine. Decent download speeds and no high ping, either.

I have changed my router's wifi channel width from 20/40/80Mhz to 20/40Mhz, which is a trick I used on my old router to have smoother streaming, or else the Steam Deck would start crapping out. But this halves my internet speed on all devices, which sucks. After doing this change, the stream was smooth but I have noticed that if I make any change to the router (like changing a setting or something or rebooting it), the chiaki stream works fine and then deteriorates after a while, so I am going to put it to the test. Really hoping this isn't the "fix" because it sucks to constantly change it back and forth to use my full internet speed :(

**Comment by JustPlainGarak** [comment]
I was having similar issues on my Steam Deck but not on my laptop (wifi connected to the same AP) or desktop (wired), both running Fedora 41 KDE with the chiaki-ng flatpak. I appear to have solved the issues by clearing all cache and config files for chiaki-ng <ins>**except for the main app config file**</ins>. These steps assume you're using the flatpak version of chiaki-ng.

1. Switch to Desktop mode.
2. Open Dolphin and navigate to `/home/deck/.var/app/`.
3. Make a quick backup of the chiaki-ng flatpak config directory: right click on `io.github.streetpea.Chiaki4deck` and click `Duplicate Here`. This will create a copy of the folder called `io.github.streetpea.Chiaki4deck copy` along with all of its contents so you can restore any files you may have delete by mistake.
4. Navigate inside the `../io.github.streetpea.Chiaki4deck/` directory. The other directories will be accessed from here.
5. Delete all contents inside the `../cache/` directory.
6. Delete `kdeglobals` and `user-dirs.dirs` inside the `../config/` directory.
7. Delete `pl_render_params.conf` inside the `../config/Chiaki/` directory. <ins>**Do not delete `Chiaki.conf`**</ins>.
8. Delete `pl_shader.cache` inside the `../data/Chiaki/Chiaki/` directory.

Now you can close Dolphin and get back into Game Mode. Chiaki-ng will regenerate all of these files upon first launch. Forcing chiaki-ng to regenerate these cache files has, so far, eliminated the strange performance issues I was encountering. It's been a few days and my streaming on Deck has been trouble free.

**Comment by mufaaf** [comment]
So...I may have found out what was causing this issue, and you won't believe what it is, lol. I am not 100% sure its that yet but here it is:

It's my Huawei MatePad Pro 13.2" tablet.

I racked my brain over the past day as to what exactly changed around me and I realized I had started using the Huawei MatePad again to watch movies and stuff. So I turned it off and kept it in my bed room. And voila, the stream was smooth again. I tried thrice at different time of the day and it worked.

So I brought the Huawei tablet back to the living room (where the PS5 and the SteamD is), turned it on and connected it to WiFi, and ho, the stream broke again. I turned off the WiFi on the tablet, but that didn't help. I took the tablet and kept it in my bedroom, and that didn't help either. I _turned it off_....and the stream went back to being smooth. Wtf?

I am going to have to test this further because this is a bit ridiculous. This was the same tablet I used to stream PS5 and PC games before I got the Steam Deck and never faced such an issue.


> I was having similar issues on my Steam Deck but not on my laptop (wifi connected to the same AP) or desktop (wired), both running Fedora 41 KDE with the chiaki-ng flatpak. I appear to have solved the issues by clearing all cache and config files for chiaki-ng **except for the main app config file**. These steps assume you're using the flatpak version of chiaki-ng.
> 
> 1. Switch to Desktop mode.
> 2. Open Dolphin and navigate to `/home/deck/.var/app/`.
> 3. Make a quick backup of the chiaki-ng flatpak config directory: right click on `io.github.streetpea.Chiaki4deck` and click `Duplicate Here`. This will create a copy of the folder called `io.github.streetpea.Chiaki4deck copy` along with all of its contents so you can restore any files you may have delete by mistake.
> 4. Navigate inside the `../io.github.streetpea.Chiaki4deck/` directory. The other directories will be accessed from here.
> 5. Delete all contents inside the `../cache/` directory.
> 6. Delete `kdeglobals` and `user-dirs.dirs` inside the `../config/` directory.
> 7. Delete `pl_render_params.conf` inside the `../config/Chiaki/` directory. **Do not delete `Chiaki.conf`**.
> 8. Delete `pl_shader.cache` inside the `../data/Chiaki/Chiaki/` directory.
> 
> Now you can close Dolphin and get back into Game Mode. Chiaki-ng will regenerate all of these files upon first launch. Forcing chiaki-ng to regenerate these cache files has, so far, eliminated the strange performance issues I was encountering. It's been a few days and my streaming on Deck has been trouble free.

Thanks for this! I am going to try and do it anyways, even if Steam Deck doesn't seem to be problem, as the issue also happens on the Ayaneo Pocket Evo, which is a Android-based handheld using PXPlay.

**Comment by streetpea** [comment]
@mufaaf it sounds like it’s causing some sort of interference which would explain your issue (or at least could be a contributing factor). Streaming videos are buffered and prioritize stability in the connection over the lowest possible latency while game streaming is the opposite so it probably only affects game streaming. Since it’s the device causing the interference it wouldn’t affect its own connection. When you have instability like that and lots of dropped packets the connection on the routers end is probably timing out resulting in potentially high usage of ram/cpu which can then cause issues for other connected devices like you’re seeing.

**Comment by mufaaf** [comment]
> @mufaaf it sounds like it’s causing some sort of interference which would explain your issue (or at least could be a contributing factor). Streaming videos are buffered and prioritize stability in the connection over the lowest possible latency while game streaming is the opposite so it probably only affects game streaming. Since it’s the device causing the interference it wouldn’t affect its own connection. When you have instability like that and lots of dropped packets the connection on the routers end is probably timing out resulting in potentially high usage of ram/cpu which can then cause issues for other connected devices like you’re seeing because it’s busy tying to connect to the ps5 and client device.
> 
> Have you tried airplane mode? Cellular signal as well as Bluetooth can also cause interference.

So, around 11 hours later, I think I can safely confirm its the Huawei tablet that was causing the issue. Just tried it and the stream was smooth as it should be write off the bat.

This is so weird. I haven't tried Airplane mode, but that's a good idea. I would hate to turn the tablet on and off every time I want to play the PS5. I shall report back soon.

**Comment by mufaaf** [comment]
I think airplane mode on the tablet works. Played a session and it was fine!

**Comment by streetpea** [comment]
@mufaaf are you fine to close this then?

**Comment by mufaaf** [comment]
Possibly, yeah. I don't think its related to Chiaki in any way anymore.

However, I have found out that the tablet is not exactly the cause of the issue. It could also be the Pocket Evo (another Android device).

Whenever I connect to PS5 using the Evo (PXPlay), the stream starts to act up. Its never smooth using that device (even though I have played on it before once), and then if I immediately shift to Deck OLED, the stream is a stuttery mess. But if i restart the PS5 and only use the Deck, its all fine.

This is absolutely bizzare stuff. Why is an Android device causing PS5 to behave like this? Anyways, yes I guess you can close it. But fascinating issue to tackle.

**Comment by streetpea** [comment]
@mufaaf i think those are 2 different issues. After exiting a stream with low connection quality,I’ve observed the next one being affected no matter the device when simulating poor connection quality because it can affect the remote play server I think which is only completely restarted when putting the console to sleep. Whereas the other issue seems to be interference with the WiFi signal causing increased packet loss which is then  enabling your ps5 to dos your router by flogging it with packets it can’t fulfill. Since the game streaming uses many more packets and udp vs tcp you see it there but not with video streaming.
