### ISSUE TITLE
Chiaki 4 Deck can’t find my PS5

### ISSUE THREAD

**Issue by ObiYoanKenobi** [streetpea/chiaki-ng#67]
Chiaki on Steam Deck can't find my PS5

I'm trying to set up Chiaki on my Steam Deck so I can play my PS5 games. My Steam Deck is on my home WiFi network (5GHZ) and my PS5 is using a wired connection but it's still on the same network.

I tried using the Remote Play app on my phone (the phone is on the same WiFi network as the Steam Deck) and it worked perfectly, my PS5 started streaming to my phone without issues.

For some reason the PS5 doesn't appear in the Chiaki app on my Steam Deck and it won't connect automatically. I've tried adding it manually but it just times out and it doesn't connect. It shows the following message: 

[I] Regist starting search
[I] Regist sending search packet
[E] Regist timed out waiting for search response
[E] Regist search failed

So, how do I get this working ? I really want to stream my PS5 to my Deck.

**Comment by Nightfire391** [comment]
You can solve this problem by putting your ps5 onto wireless not wired

**Comment by ObiYoanKenobi** [comment]
> You can solve this problem by putting your ps5 onto wireless not wired
> 
> It cant find your ps5 when your ps5 is not on the wireless network

That’s not really a solution. The WiFi router isn’t in the same room as the PS, so wireless. Wired is much faster and stable than wireless. 

Also, the WiFi and the wired connection are still on the same network, they aren’t two different networks. 

For example, my TV is wired but my tablet is on the wireless network but my tablet automatically finds the TV and it allows me to cast video to it.

**Comment by streetpea** [comment]
This likely has to do with router settings, either at the network level or device level. Your device needs access to wired devices on the network. Given the router is configured to allow this for your Steam Deck you should be able to connect. I am able to connect to my wired PS5 via my wireless network but can't do it if using the guest network as devices on that network don't have access to wired devices.
