### ISSUE TITLE
Having DualSense haptics, adaptive triggers and always-on gyro at the same time for all PS5 games

### ISSUE THREAD

**Issue by CarlosVR2** [streetpea/chiaki-ng#69]
Hello! First of all, congratulations for your awesome work on Chiaki4deck.

I'm enjoying having the DualSense haptics and adaptive triggers on supported PS5 games, but, as a Steam Deck user, I'm also kind of spoiled to using the gyro for all kinds of games.

I know Chiaki4deck supports the DualSense gyro for PS5 games that support it natively, but, is there a way to use the gyro as a joystick for any game like Steam Input does, while still having the DualSense haptics and adaptive triggers?

Thanks in advance!

**Comment by streetpea** [comment]
The haptics audio device doesn't show up when Steam input is enabled so I don't think this is possible with the current implementation.

**Comment by CarlosVR2** [comment]
Hello again! Thank you for your reply @streetpea.

My goal is to have the DualSense gyro ON even for unsupported PS5 games while keeping active the haptics and adaptive triggers _without using Steam Input at all_ (having it disabled for the DualSense in Chiaki4deck).

So far, the closest I have been to a solution is to use the software **AntiMicroX** to map the DualSense gyro axes to the keys Chiaki4deck assigns to the right stick (-, =, PgUp, PgDn). Additionally, I use the AntiMicroX profile switching option to have two profiles: one with gyro on and another with gyro off, and then I assign a DualSense button (L3) to turn gyro on and off by switching the profiles.

Once you add AntimicroX as a Non-Steam app, you can run it in Game Mode and keep it active in the background while you use Chiaki4deck. Note you also have to disable Steam Input for the DualSense in the AntimicroX Steam settings to be detected properly (PS5 controller instead of Steam Virtual Gamepad).

While this method works, the gyro behavior is somewhat jerky and not as smooth as using the Steam Deck gyro or the DualSense gyro with Steam Input. Maybe it's because it's mapping Gyro->Key->Right Stick?

This was tested with both versions 1.3.1 and 1.3.2, in the same Wi-Fi network and over the internet as well.

Any comments are appreciated!

**Steam DualSense controller settings for Chiaki4deck and AntiMicroX:**
<img width="1440" alt="DualSense Steam Input disabled" src="https://github.com/streetpea/chiaki4deck/assets/135720937/8ee07c3a-fc89-4460-96c1-acfab300b5ac">

**AntiMicroX screen for the DualSense. Note the _Gyroscope_ and _LS Click_ (L3) settings:**
<img width="1440" alt="AntimicroX settings" src="https://github.com/streetpea/chiaki4deck/assets/135720937/cb28a97f-baeb-4038-9288-3a82925ab2b5">
